<?php
/**
 * EndpointsApiTest
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bandwidth\Test\Unit\Api;

use Bandwidth\Configuration;
use Bandwidth\Api\EndpointsApi;
use Bandwidth\Model\CreateEndpointResponse;
use Bandwidth\Model\CreateEndpointResponseData;
use Bandwidth\Model\CreateWebRtcConnectionRequest;
use Bandwidth\Model\Endpoint;
use Bandwidth\Model\EndpointDirectionEnum;
use Bandwidth\Model\EndpointResponse;
use Bandwidth\Model\Endpoints;
use Bandwidth\Model\EndpointStatusEnum;
use Bandwidth\Model\EndpointTypeEnum;
use Bandwidth\Model\ListEndpointsResponse;
use Bandwidth\Model\Page;

use PHPUnit\Framework\TestCase;

/**
 * EndpointsApiTest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EndpointsApiTest extends TestCase
{

    private static EndpointsApi $apiInstance;
    private static string $account_id;

    private static string $endpoint_id = 'test-endpoint-id';
    private static string $bxml = '<?xml version="1.0" encoding="UTF-8"?><Bxml><SpeakSentence>Hello</SpeakSentence></Bxml>';

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = (new Configuration())
            ->setAccessToken("abcd1234")
            ->setIgnoreOperationHosts(true)
            ->setHost("http://127.0.0.1:4010");

        self::$apiInstance = new EndpointsApi(config: $config);

        self::$account_id = getenv("BW_ACCOUNT_ID");
    }

    /**
     * Test case for createEndpoint
     *
     * Create Endpoint.
     *
     */
    public function testCreateEndpoint()
    {
        $endpoint_body = new CreateWebRtcConnectionRequest([
            'type' => EndpointTypeEnum::WEBRTC,
            'direction' => EndpointDirectionEnum::BIDIRECTIONAL
        ]);

        [$data, $status_code] = self::$apiInstance->createEndpointWithHttpInfo(
            self::$account_id,
            $endpoint_body
        );

        $this->assertEquals(201, $status_code);
        $this->assertInstanceOf(CreateEndpointResponse::class, $data);
        $this->assertIsArray($data->getLinks());
        $this->assertInstanceOf(CreateEndpointResponseData::class, $data->getData());
        $this->assertIsString($data->getData()->getEndpointId());
        $this->assertIsString($data->getData()->getToken());
        $this->assertInstanceOf(EndpointTypeEnum::class, $data->getData()->getType());
        $this->assertInstanceOf(EndpointStatusEnum::class, $data->getData()->getStatus());
        $this->assertInstanceOf(\DateTime::class, $data->getData()->getCreationTimestamp());
        $this->assertInstanceOf(\DateTime::class, $data->getData()->getExpirationTimestamp());
        $this->assertIsString($data->getData()->getTag());
        $this->assertIsArray($data->getData()->getDevices());
        $this->assertIsArray($data->getErrors());
    }

    /**
     * Test case for deleteEndpoint
     *
     * Delete Endpoint.
     *
     */
    public function testDeleteEndpoint()
    {
        [, $status_code] = self::$apiInstance->deleteEndpointWithHttpInfo(
            self::$account_id,
            self::$endpoint_id
        );

        $this->assertEquals(204, $status_code);
    }

    /**
     * Test case for getEndpoint
     *
     * Get Endpoint.
     *
     */
    public function testGetEndpoint()
    {
        [$data, $status_code] = self::$apiInstance->getEndpointWithHttpInfo(
            self::$account_id,
            self::$endpoint_id
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(EndpointResponse::class, $data);
        $this->assertIsArray($data->getLinks());
        $this->assertInstanceOf(Endpoint::class, $data->getData());
        $this->assertIsString($data->getData()->getEndpointId());
        $this->assertInstanceOf(EndpointTypeEnum::class, $data->getData()->getType());
        $this->assertInstanceOf(EndpointStatusEnum::class, $data->getData()->getStatus());
        $this->assertInstanceOf(\DateTime::class, $data->getData()->getCreationTimestamp());
        $this->assertInstanceOf(\DateTime::class, $data->getData()->getExpirationTimestamp());
        $this->assertIsString($data->getData()->getTag());
        $this->assertIsArray($data->getData()->getDevices());
        $this->assertIsArray($data->getErrors());
    }

    /**
     * Test case for listEndpoints
     *
     * List Endpoints.
     *
     */
    public function testListEndpoints()
    {
        [$data, $status_code] = self::$apiInstance->listEndpointsWithHttpInfo(
            self::$account_id
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(ListEndpointsResponse::class, $data);
        $this->assertIsArray($data->getLinks());
        $this->assertIsArray($data->getData());
        $this->assertInstanceOf(Endpoints::class, $data->getData()[0]);
        $this->assertIsString($data->getData()[0]->getEndpointId());
        $this->assertInstanceOf(EndpointTypeEnum::class, $data->getData()[0]->getType());
        $this->assertInstanceOf(EndpointStatusEnum::class, $data->getData()[0]->getStatus());
        $this->assertInstanceOf(\DateTime::class, $data->getData()[0]->getCreationTimestamp());
        $this->assertInstanceOf(\DateTime::class, $data->getData()[0]->getExpirationTimestamp());
        $this->assertIsString($data->getData()[0]->getTag());
        $this->assertInstanceOf(Page::class, $data->getPage());
        $this->assertIsArray($data->getErrors());
    }

    /**
     * Test case for updateEndpointBxml
     *
     * Update Endpoint BXML.
     *
     */
    public function testUpdateEndpointBxml()
    {
        [, $status_code] = self::$apiInstance->updateEndpointBxmlWithHttpInfo(
            self::$account_id,
            self::$endpoint_id,
            self::$bxml
        );

        $this->assertEquals(204, $status_code);
    }
}
