<?php
/**
 * MediaApiTest
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bandwidth\Test\Unit\Api;

use Bandwidth\Configuration;
use Bandwidth\Api\MediaApi;
use Bandwidth\Model\Media;
use SplFileObject;

use PHPUnit\Framework\TestCase;

/**
 * MediaApiTest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaApiTest extends TestCase
{

    private static MediaApi $apiInstance;
    private static string $account_id;

    private static string $media_name = 'php_binary_media';
    private static SplFileObject $media_file;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()
            ->setAccessToken("abcd1234")
            ->setIgnoreOperationHosts(true)
            ->setHost("http://127.0.0.1:4010");

        self::$apiInstance = new MediaApi(config: $config);

        self::$account_id = getenv("BW_ACCOUNT_ID");

        $path = tempnam(sys_get_temp_dir(), 'bw_media_');
        file_put_contents($path, "123456");
        self::$media_file = new SplFileObject($path, 'rb');
    }

    /**
     * Test case for deleteMedia
     *
     * Delete Media.
     *
     */
    public function testDeleteMedia()
    {
        [, $status_code] = self::$apiInstance->deleteMediaWithHttpInfo(
            self::$account_id,
            self::$media_name
        );

        $this->assertEquals(204, $status_code);
    }

    /**
     * Test case for getMedia
     *
     * Get Media.
     *
     */
    public function testGetMedia()
    {
        self::markTestSkipped("Can't set the correct Accept header for Prism");

        [$data, $status_code] = self::$apiInstance->getMediaWithHttpInfo(
            self::$account_id,
            self::$media_name
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(SplFileObject::class, $data);
    }

    /**
     * Test case for listMedia
     *
     * List Media.
     *
     */
    public function testListMedia()
    {
        [$data, $status_code] = self::$apiInstance->listMediaWithHttpInfo(
            self::$account_id
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(Media::class, $data[0]);
        $this->assertIsString($data[0]->getContent());
        $this->assertIsInt($data[0]->getContentLength());
        $this->assertIsString($data[0]->getMediaName());
    }

    /**
     * Test case for uploadMedia
     *
     * Upload Media.
     *
     */
    public function testUploadMedia()
    {
        self::markTestSkipped("Can't set the correct Content-Type and Accept headers for Prism");

        [, $status_code] = self::$apiInstance->uploadMediaWithHttpInfo(
            self::$account_id,
            self::$media_name,
            self::$media_file,
            content_type: 'image/jpeg',
            cache_control: 'no-cache'
        );

        $this->assertEquals(204, $status_code);
    }
}
