<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BandwidthLib\MultiFactorAuth;

use BandwidthLib\MultiFactorAuth\Controllers;

/**
 * BandwidthLib client class
 */
class MultiFactorAuthClient
{
    private $config;
    public function __construct($config)
    {
        $this->config = $config;
    }


    private $mFA;

    /**
     * Provides access to MFA controller
     * @return Controllers\MFAController
     */
    public function getMFA()
    {
        if ($this->mFA == null) {
            $this->mFA = new Controllers\MFAController($this->config);
        }
        return $this->mFA;
    }
}
