<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Exceptions;

use BandwidthLib\APIHelper;

/**
 * @todo Write general description for this model
 */
class ErrorResponseException extends \BandwidthLib\APIException
{
    /**
     * @todo Write general description for this property
     * @var mixed|null $type public property
     */
    public $type;

    /**
     * @todo Write general description for this property
     * @var string|null $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @var string|null $id public property
     */
    public $id;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false);
    }
}
