<?php
/**
 * MFAApiTest
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bandwidth\Test\Smoke;

use Bandwidth\Configuration;
use Bandwidth\Api\MFAApi;
use Bandwidth\Model\CodeRequest;
use Bandwidth\Model\MessagingCodeResponse;
use Bandwidth\Model\VerifyCodeRequest;
use Bandwidth\Model\VerifyCodeResponse;
use Bandwidth\Model\VoiceCodeResponse;

use PHPUnit\Framework\TestCase;

/**
 * MFAApiTest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MFAApiTest extends TestCase
{
    private static MFAApi $apiInstance;
    private static string $account_id;
    private static string $bw_number;
    private static string $user_number;
    private static string $bw_messaging_application_id;
    private static string $bw_voice_application_id;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = (new Configuration())
            ->setUsername(getenv("BW_USERNAME"))
            ->setPassword(getenv("BW_PASSWORD"));

        self::$apiInstance = new MFAApi(config: $config);

        self::$account_id = getenv("BW_ACCOUNT_ID");
        self::$bw_number = getenv("BW_NUMBER");
        self::$user_number = getenv("USER_NUMBER");
        self::$bw_messaging_application_id = getenv("BW_MESSAGING_APPLICATION_ID");
        self::$bw_voice_application_id = getenv("BW_VOICE_APPLICATION_ID");
    }

    /**
     * Test case for generateMessagingCode
     *
     * Messaging Authentication Code.
     *
     */
    public function testGenerateMessagingCode()
    {
        $request = new CodeRequest([
            'to' => self::$user_number,
            'from' => self::$bw_number,
            'application_id' => self::$bw_messaging_application_id,
            'scope' => 'scope',
            'message' => 'Your temporary {NAME} {SCOPE} code is {CODE}',
            'digits' => 6
        ]);

        [$data, $status_code] = self::$apiInstance->generateMessagingCodeWithHttpInfo(
            self::$account_id,
            $request
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(MessagingCodeResponse::class, $data);
        $this->assertIsString($data->getMessageId());
    }

    /**
     * Test case for generateVoiceCode
     *
     * Voice Authentication Code.
     *
     */
    public function testGenerateVoiceCode()
    {
        $request = new CodeRequest([
            'to' => self::$user_number,
            'from' => self::$bw_number,
            'application_id' => self::$bw_voice_application_id,
            'scope' => 'scope',
            'message' => 'Your temporary {NAME} {SCOPE} code is {CODE}',
            'digits' => 6
        ]);

        [$data, $status_code] = self::$apiInstance->generateVoiceCodeWithHttpInfo(
            self::$account_id,
            $request
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(VoiceCodeResponse::class, $data);
        $this->assertIsString($data->getCallId());
    }

    /**
     * Test case for verifyCode
     *
     * Verify Authentication Code.
     *
     */
    public function testVerifyCode()
    {
        // Use a random TN to avoid rate limiting
        $random_tn = '+1' . (string) rand(1111111111, 9999999999);

        $request = new VerifyCodeRequest([
            'to' => $random_tn,
            'scope' => '2FA',
            'expiration_time_in_minutes' => 3,
            'code' => '123456'
        ]);

        [$data, $status_code] = self::$apiInstance->verifyCodeWithHttpInfo(
            self::$account_id,
            $request
        );

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(VerifyCodeResponse::class, $data);
        $this->assertFalse($data->getValid());
    }
}
