<?php
/**
 * TollFreeVerificationApiTest
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bandwidth\Test\Smoke;

use Bandwidth\Configuration;
use Bandwidth\Api\TollFreeVerificationApi;

use PHPUnit\Framework\TestCase;

/**
 * TollFreeVerificationApiTest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TollFreeVerificationApiTest extends TestCase
{
    private static TollFreeVerificationApi $apiInstance;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()
            ->setClientId(getenv("BW_CLIENT_ID"))
            ->setClientSecret(getenv("BW_CLIENT_SECRET"));

        self::$apiInstance = new TollFreeVerificationApi(config: $config);
    }

    /**
     * Test case for createWebhookSubscription
     *
     * Create Webhook Subscription.
     *
     */
    public function testCreateWebhookSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteVerificationRequest
     *
     * Delete a Toll-Free Verification Submission.
     *
     */
    public function testDeleteVerificationRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebhookSubscription
     *
     * Delete Webhook Subscription.
     *
     */
    public function testDeleteWebhookSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTollFreeVerificationStatus
     *
     * Get Toll-Free Verification Status.
     *
     */
    public function testGetTollFreeVerificationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTollFreeUseCases
     *
     * List Toll-Free Use Cases.
     *
     */
    public function testListTollFreeUseCases()
    {
        [$data, $status_code] = self::$apiInstance->listTollFreeUseCasesWithHttpInfo();

        $this->assertEquals(200, $status_code);
        $this->assertIsArray($data);
    }

    /**
     * Test case for listWebhookSubscriptions
     *
     * List Webhook Subscriptions.
     *
     */
    public function testListWebhookSubscriptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestTollFreeVerification
     *
     * Request Toll-Free Verification.
     *
     */
    public function testRequestTollFreeVerification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTollFreeVerificationRequest
     *
     * Update Toll-Free Verification Request.
     *
     */
    public function testUpdateTollFreeVerificationRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebhookSubscription
     *
     * Update Webhook Subscription.
     *
     */
    public function testUpdateWebhookSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
