<?php
/**
 * StatisticsApiTest
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bandwidth\Test\Api;

use Bandwidth\Configuration;
use Bandwidth\Api\StatisticsApi;
use Bandwidth\Model\AccountStatistics;

use PHPUnit\Framework\TestCase;

/**
 * StatisticsApiTest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatisticsApiTest extends TestCase
{
    private static StatisticsApi $apiInstance;
    private static string $account_id;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()
            ->setUsername(getenv("BW_USERNAME"))
            ->setPassword(getenv("BW_PASSWORD"));

        self::$apiInstance = new StatisticsApi(config: $config);

        self::$account_id = getenv("BW_ACCOUNT_ID");
    }

    /**
     * Test case for getStatistics
     *
     * Get Account Statistics.
     *
     */
    public function testGetStatistics()
    {
        [$data, $status_code] = self::$apiInstance->getStatisticsWithHttpInfo(self::$account_id);

        $this->assertEquals(200, $status_code);
        $this->assertInstanceOf(AccountStatistics::class, $data);
        $this->assertIsInt($data->getCurrentCallQueueSize());
        $this->assertIsInt($data->getMaxCallQueueSize());
    }
}
