<?php
/**
 * TranscriptionsApiTest
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bandwidth\Test\Api;

use Bandwidth\Configuration;
use Bandwidth\ApiException;
use Bandwidth\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TranscriptionsApiTest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranscriptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteRealTimeTranscription
     *
     * Delete Real-time Transcription.
     *
     */
    public function testDeleteRealTimeTranscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRealTimeTranscription
     *
     * Get Real-time Transcription.
     *
     */
    public function testGetRealTimeTranscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRealTimeTranscriptions
     *
     * List Real-time Transcriptions.
     *
     */
    public function testListRealTimeTranscriptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
