<?php

declare(strict_types=1);

/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Messaging\Models;

class PageInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $prevPage;

    /**
     * @var string|null
     */
    private $nextPage;

    /**
     * @var string|null
     */
    private $prevPageToken;

    /**
     * @var string|null
     */
    private $nextPageToken;

    /**
     * Returns Prev Page.
     *
     * The link to the previous page for pagination
     */
    public function getPrevPage(): ?string
    {
        return $this->prevPage;
    }

    /**
     * Sets Prev Page.
     *
     * The link to the previous page for pagination
     *
     * @maps prevPage
     */
    public function setPrevPage(?string $prevPage): void
    {
        $this->prevPage = $prevPage;
    }

    /**
     * Returns Next Page.
     *
     * The link to the next page for pagination
     */
    public function getNextPage(): ?string
    {
        return $this->nextPage;
    }

    /**
     * Sets Next Page.
     *
     * The link to the next page for pagination
     *
     * @maps nextPage
     */
    public function setNextPage(?string $nextPage): void
    {
        $this->nextPage = $nextPage;
    }

    /**
     * Returns Prev Page Token.
     *
     * The isolated pagination token for the previous page
     */
    public function getPrevPageToken(): ?string
    {
        return $this->prevPageToken;
    }

    /**
     * Sets Prev Page Token.
     *
     * The isolated pagination token for the previous page
     *
     * @maps prevPageToken
     */
    public function setPrevPageToken(?string $prevPageToken): void
    {
        $this->prevPageToken = $prevPageToken;
    }

    /**
     * Returns Next Page Token.
     *
     * The isolated pagination token for the next page
     */
    public function getNextPageToken(): ?string
    {
        return $this->nextPageToken;
    }

    /**
     * Sets Next Page Token.
     *
     * The isolated pagination token for the next page
     *
     * @maps nextPageToken
     */
    public function setNextPageToken(?string $nextPageToken): void
    {
        $this->nextPageToken = $nextPageToken;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['prevPage']      = $this->prevPage;
        $json['nextPage']      = $this->nextPage;
        $json['prevPageToken'] = $this->prevPageToken;
        $json['nextPageToken'] = $this->nextPageToken;

        return array_filter($json, function ($val) {
            return $val !== null;
        });
    }
}
