apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: php-sdk-location
  description: Links to additional entities in the php-sdk repository.
  annotations:
    github.com/project-slug: Bandwidth/php-sdk
spec:
  targets:
    - ./component.yaml
