<?php
/**
 * CreateCallResponse
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bandwidth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Bandwidth\ObjectSerializer;

/**
 * CreateCallResponse Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateCallResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'createCallResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'application_id' => 'string',
        'account_id' => 'string',
        'call_id' => 'string',
        'to' => 'string',
        'from' => 'string',
        'enqueued_time' => '\DateTime',
        'call_url' => 'string',
        'call_timeout' => 'float',
        'callback_timeout' => 'float',
        'tag' => 'string',
        'answer_method' => '\Bandwidth\Model\CallbackMethodEnum',
        'answer_url' => 'string',
        'answer_fallback_method' => '\Bandwidth\Model\CallbackMethodEnum',
        'answer_fallback_url' => 'string',
        'disconnect_method' => '\Bandwidth\Model\CallbackMethodEnum',
        'disconnect_url' => 'string',
        'username' => 'string',
        'password' => 'string',
        'fallback_username' => 'string',
        'fallback_password' => 'string',
        'priority' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'application_id' => null,
        'account_id' => null,
        'call_id' => null,
        'to' => null,
        'from' => null,
        'enqueued_time' => 'date-time',
        'call_url' => 'uri',
        'call_timeout' => 'double',
        'callback_timeout' => 'double',
        'tag' => null,
        'answer_method' => null,
        'answer_url' => 'uri',
        'answer_fallback_method' => null,
        'answer_fallback_url' => 'uri',
        'disconnect_method' => null,
        'disconnect_url' => 'uri',
        'username' => null,
        'password' => null,
        'fallback_username' => null,
        'fallback_password' => null,
        'priority' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'application_id' => false,
        'account_id' => false,
        'call_id' => false,
        'to' => false,
        'from' => false,
        'enqueued_time' => true,
        'call_url' => false,
        'call_timeout' => false,
        'callback_timeout' => false,
        'tag' => true,
        'answer_method' => true,
        'answer_url' => false,
        'answer_fallback_method' => true,
        'answer_fallback_url' => true,
        'disconnect_method' => true,
        'disconnect_url' => true,
        'username' => true,
        'password' => true,
        'fallback_username' => true,
        'fallback_password' => true,
        'priority' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'application_id' => 'applicationId',
        'account_id' => 'accountId',
        'call_id' => 'callId',
        'to' => 'to',
        'from' => 'from',
        'enqueued_time' => 'enqueuedTime',
        'call_url' => 'callUrl',
        'call_timeout' => 'callTimeout',
        'callback_timeout' => 'callbackTimeout',
        'tag' => 'tag',
        'answer_method' => 'answerMethod',
        'answer_url' => 'answerUrl',
        'answer_fallback_method' => 'answerFallbackMethod',
        'answer_fallback_url' => 'answerFallbackUrl',
        'disconnect_method' => 'disconnectMethod',
        'disconnect_url' => 'disconnectUrl',
        'username' => 'username',
        'password' => 'password',
        'fallback_username' => 'fallbackUsername',
        'fallback_password' => 'fallbackPassword',
        'priority' => 'priority'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'application_id' => 'setApplicationId',
        'account_id' => 'setAccountId',
        'call_id' => 'setCallId',
        'to' => 'setTo',
        'from' => 'setFrom',
        'enqueued_time' => 'setEnqueuedTime',
        'call_url' => 'setCallUrl',
        'call_timeout' => 'setCallTimeout',
        'callback_timeout' => 'setCallbackTimeout',
        'tag' => 'setTag',
        'answer_method' => 'setAnswerMethod',
        'answer_url' => 'setAnswerUrl',
        'answer_fallback_method' => 'setAnswerFallbackMethod',
        'answer_fallback_url' => 'setAnswerFallbackUrl',
        'disconnect_method' => 'setDisconnectMethod',
        'disconnect_url' => 'setDisconnectUrl',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'fallback_username' => 'setFallbackUsername',
        'fallback_password' => 'setFallbackPassword',
        'priority' => 'setPriority'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'application_id' => 'getApplicationId',
        'account_id' => 'getAccountId',
        'call_id' => 'getCallId',
        'to' => 'getTo',
        'from' => 'getFrom',
        'enqueued_time' => 'getEnqueuedTime',
        'call_url' => 'getCallUrl',
        'call_timeout' => 'getCallTimeout',
        'callback_timeout' => 'getCallbackTimeout',
        'tag' => 'getTag',
        'answer_method' => 'getAnswerMethod',
        'answer_url' => 'getAnswerUrl',
        'answer_fallback_method' => 'getAnswerFallbackMethod',
        'answer_fallback_url' => 'getAnswerFallbackUrl',
        'disconnect_method' => 'getDisconnectMethod',
        'disconnect_url' => 'getDisconnectUrl',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'fallback_username' => 'getFallbackUsername',
        'fallback_password' => 'getFallbackPassword',
        'priority' => 'getPriority'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('application_id', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('call_id', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('enqueued_time', $data ?? [], null);
        $this->setIfExists('call_url', $data ?? [], null);
        $this->setIfExists('call_timeout', $data ?? [], null);
        $this->setIfExists('callback_timeout', $data ?? [], null);
        $this->setIfExists('tag', $data ?? [], null);
        $this->setIfExists('answer_method', $data ?? [], null);
        $this->setIfExists('answer_url', $data ?? [], null);
        $this->setIfExists('answer_fallback_method', $data ?? [], null);
        $this->setIfExists('answer_fallback_url', $data ?? [], null);
        $this->setIfExists('disconnect_method', $data ?? [], null);
        $this->setIfExists('disconnect_url', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('fallback_username', $data ?? [], null);
        $this->setIfExists('fallback_password', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['application_id'] === null) {
            $invalidProperties[] = "'application_id' can't be null";
        }
        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if ($this->container['call_id'] === null) {
            $invalidProperties[] = "'call_id' can't be null";
        }
        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ($this->container['call_url'] === null) {
            $invalidProperties[] = "'call_url' can't be null";
        }
        if ($this->container['answer_method'] === null && !$this->isNullableSetToNull('answer_method')) {
            $invalidProperties[] = "'answer_method' is required";
        }
        if ($this->container['answer_url'] === null) {
            $invalidProperties[] = "'answer_url' can't be null";
        }
        if ($this->container['disconnect_method'] === null && !$this->isNullableSetToNull('disconnect_method')) {
            $invalidProperties[] = "'disconnect_method' is required";
        }
        if (!is_null($this->container['username']) && (mb_strlen($this->container['username']) > 1024)) {
            $invalidProperties[] = "invalid value for 'username', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['password']) && (mb_strlen($this->container['password']) > 1024)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['fallback_username']) && (mb_strlen($this->container['fallback_username']) > 1024)) {
            $invalidProperties[] = "invalid value for 'fallback_username', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['fallback_password']) && (mb_strlen($this->container['fallback_password']) > 1024)) {
            $invalidProperties[] = "invalid value for 'fallback_password', the character length must be smaller than or equal to 1024.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets application_id
     *
     * @return string
     */
    public function getApplicationId(): string
    {
        return $this->container['application_id'];
    }

    /**
     * Sets application_id
     *
     * @param string $application_id The id of the application associated with the `from` number.
     *
     * @return $this
     */
    public function setApplicationId(string $application_id): static
    {
        if (is_null($application_id)) {
            throw new InvalidArgumentException('non-nullable application_id cannot be null');
        }
        $this->container['application_id'] = $application_id;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string
     */
    public function getAccountId(): string
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string $account_id The bandwidth account ID associated with the call.
     *
     * @return $this
     */
    public function setAccountId(string $account_id): static
    {
        if (is_null($account_id)) {
            throw new InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets call_id
     *
     * @return string
     */
    public function getCallId(): string
    {
        return $this->container['call_id'];
    }

    /**
     * Sets call_id
     *
     * @param string $call_id Programmable Voice API Call ID.
     *
     * @return $this
     */
    public function setCallId(string $call_id): static
    {
        if (is_null($call_id)) {
            throw new InvalidArgumentException('non-nullable call_id cannot be null');
        }
        $this->container['call_id'] = $call_id;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string
     */
    public function getTo(): string
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string $to Recipient of the outgoing call.
     *
     * @return $this
     */
    public function setTo(string $to): static
    {
        if (is_null($to)) {
            throw new InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom(): string
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from Phone number that created the outbound call.
     *
     * @return $this
     */
    public function setFrom(string $from): static
    {
        if (is_null($from)) {
            throw new InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets enqueued_time
     *
     * @return \DateTime|null
     */
    public function getEnqueuedTime(): ?\DateTime
    {
        return $this->container['enqueued_time'];
    }

    /**
     * Sets enqueued_time
     *
     * @param \DateTime|null $enqueued_time The time at which the call was accepted into the queue.
     *
     * @return $this
     */
    public function setEnqueuedTime(?\DateTime $enqueued_time): static
    {
        if (is_null($enqueued_time)) {
            array_push($this->openAPINullablesSetToNull, 'enqueued_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enqueued_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enqueued_time'] = $enqueued_time;

        return $this;
    }

    /**
     * Gets call_url
     *
     * @return string
     */
    public function getCallUrl(): string
    {
        return $this->container['call_url'];
    }

    /**
     * Sets call_url
     *
     * @param string $call_url The URL to update this call's state.
     *
     * @return $this
     */
    public function setCallUrl(string $call_url): static
    {
        if (is_null($call_url)) {
            throw new InvalidArgumentException('non-nullable call_url cannot be null');
        }
        $this->container['call_url'] = $call_url;

        return $this;
    }

    /**
     * Gets call_timeout
     *
     * @return float|null
     */
    public function getCallTimeout(): ?float
    {
        return $this->container['call_timeout'];
    }

    /**
     * Sets call_timeout
     *
     * @param float|null $call_timeout The timeout (in seconds) for the callee to answer the call after it starts ringing.
     *
     * @return $this
     */
    public function setCallTimeout(?float $call_timeout): static
    {
        if (is_null($call_timeout)) {
            throw new InvalidArgumentException('non-nullable call_timeout cannot be null');
        }
        $this->container['call_timeout'] = $call_timeout;

        return $this;
    }

    /**
     * Gets callback_timeout
     *
     * @return float|null
     */
    public function getCallbackTimeout(): ?float
    {
        return $this->container['callback_timeout'];
    }

    /**
     * Sets callback_timeout
     *
     * @param float|null $callback_timeout This is the timeout (in seconds) to use when delivering webhooks for the call.
     *
     * @return $this
     */
    public function setCallbackTimeout(?float $callback_timeout): static
    {
        if (is_null($callback_timeout)) {
            throw new InvalidArgumentException('non-nullable callback_timeout cannot be null');
        }
        $this->container['callback_timeout'] = $callback_timeout;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string|null
     */
    public function getTag(): ?string
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string|null $tag Custom tag value.
     *
     * @return $this
     */
    public function setTag(?string $tag): static
    {
        if (is_null($tag)) {
            array_push($this->openAPINullablesSetToNull, 'tag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets answer_method
     *
     * @return \Bandwidth\Model\CallbackMethodEnum|null
     */
    public function getAnswerMethod(): ?\Bandwidth\Model\CallbackMethodEnum
    {
        return $this->container['answer_method'];
    }

    /**
     * Sets answer_method
     *
     * @param \Bandwidth\Model\CallbackMethodEnum|null $answer_method answer_method
     *
     * @return $this
     */
    public function setAnswerMethod(?\Bandwidth\Model\CallbackMethodEnum $answer_method): static
    {
        if (is_null($answer_method)) {
            array_push($this->openAPINullablesSetToNull, 'answer_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['answer_method'] = $answer_method;

        return $this;
    }

    /**
     * Gets answer_url
     *
     * @return string
     */
    public function getAnswerUrl(): string
    {
        return $this->container['answer_url'];
    }

    /**
     * Sets answer_url
     *
     * @param string $answer_url URL to deliver the `answer` event webhook.
     *
     * @return $this
     */
    public function setAnswerUrl(string $answer_url): static
    {
        if (is_null($answer_url)) {
            throw new InvalidArgumentException('non-nullable answer_url cannot be null');
        }
        $this->container['answer_url'] = $answer_url;

        return $this;
    }

    /**
     * Gets answer_fallback_method
     *
     * @return \Bandwidth\Model\CallbackMethodEnum|null
     */
    public function getAnswerFallbackMethod(): ?\Bandwidth\Model\CallbackMethodEnum
    {
        return $this->container['answer_fallback_method'];
    }

    /**
     * Sets answer_fallback_method
     *
     * @param \Bandwidth\Model\CallbackMethodEnum|null $answer_fallback_method answer_fallback_method
     *
     * @return $this
     */
    public function setAnswerFallbackMethod(?\Bandwidth\Model\CallbackMethodEnum $answer_fallback_method): static
    {
        if (is_null($answer_fallback_method)) {
            array_push($this->openAPINullablesSetToNull, 'answer_fallback_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_fallback_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['answer_fallback_method'] = $answer_fallback_method;

        return $this;
    }

    /**
     * Gets answer_fallback_url
     *
     * @return string|null
     */
    public function getAnswerFallbackUrl(): ?string
    {
        return $this->container['answer_fallback_url'];
    }

    /**
     * Sets answer_fallback_url
     *
     * @param string|null $answer_fallback_url Fallback URL to deliver the `answer` event webhook.
     *
     * @return $this
     */
    public function setAnswerFallbackUrl(?string $answer_fallback_url): static
    {
        if (is_null($answer_fallback_url)) {
            array_push($this->openAPINullablesSetToNull, 'answer_fallback_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_fallback_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['answer_fallback_url'] = $answer_fallback_url;

        return $this;
    }

    /**
     * Gets disconnect_method
     *
     * @return \Bandwidth\Model\CallbackMethodEnum|null
     */
    public function getDisconnectMethod(): ?\Bandwidth\Model\CallbackMethodEnum
    {
        return $this->container['disconnect_method'];
    }

    /**
     * Sets disconnect_method
     *
     * @param \Bandwidth\Model\CallbackMethodEnum|null $disconnect_method disconnect_method
     *
     * @return $this
     */
    public function setDisconnectMethod(?\Bandwidth\Model\CallbackMethodEnum $disconnect_method): static
    {
        if (is_null($disconnect_method)) {
            array_push($this->openAPINullablesSetToNull, 'disconnect_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disconnect_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disconnect_method'] = $disconnect_method;

        return $this;
    }

    /**
     * Gets disconnect_url
     *
     * @return string|null
     */
    public function getDisconnectUrl(): ?string
    {
        return $this->container['disconnect_url'];
    }

    /**
     * Sets disconnect_url
     *
     * @param string|null $disconnect_url URL to deliver the `disconnect` event webhook.
     *
     * @return $this
     */
    public function setDisconnectUrl(?string $disconnect_url): static
    {
        if (is_null($disconnect_url)) {
            array_push($this->openAPINullablesSetToNull, 'disconnect_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disconnect_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disconnect_url'] = $disconnect_url;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username Basic auth username.
     *
     * @return $this
     */
    public function setUsername(?string $username): static
    {
        if (is_null($username)) {
            array_push($this->openAPINullablesSetToNull, 'username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($username) && (mb_strlen($username) > 1024)) {
            throw new InvalidArgumentException('invalid length for $username when calling CreateCallResponse., must be smaller than or equal to 1024.');
        }

        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password Basic auth password.
     *
     * @return $this
     */
    public function setPassword(?string $password): static
    {
        if (is_null($password)) {
            array_push($this->openAPINullablesSetToNull, 'password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($password) && (mb_strlen($password) > 1024)) {
            throw new InvalidArgumentException('invalid length for $password when calling CreateCallResponse., must be smaller than or equal to 1024.');
        }

        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets fallback_username
     *
     * @return string|null
     */
    public function getFallbackUsername(): ?string
    {
        return $this->container['fallback_username'];
    }

    /**
     * Sets fallback_username
     *
     * @param string|null $fallback_username Basic auth username.
     *
     * @return $this
     */
    public function setFallbackUsername(?string $fallback_username): static
    {
        if (is_null($fallback_username)) {
            array_push($this->openAPINullablesSetToNull, 'fallback_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fallback_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($fallback_username) && (mb_strlen($fallback_username) > 1024)) {
            throw new InvalidArgumentException('invalid length for $fallback_username when calling CreateCallResponse., must be smaller than or equal to 1024.');
        }

        $this->container['fallback_username'] = $fallback_username;

        return $this;
    }

    /**
     * Gets fallback_password
     *
     * @return string|null
     */
    public function getFallbackPassword(): ?string
    {
        return $this->container['fallback_password'];
    }

    /**
     * Sets fallback_password
     *
     * @param string|null $fallback_password Basic auth password.
     *
     * @return $this
     */
    public function setFallbackPassword(?string $fallback_password): static
    {
        if (is_null($fallback_password)) {
            array_push($this->openAPINullablesSetToNull, 'fallback_password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fallback_password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($fallback_password) && (mb_strlen($fallback_password) > 1024)) {
            throw new InvalidArgumentException('invalid length for $fallback_password when calling CreateCallResponse., must be smaller than or equal to 1024.');
        }

        $this->container['fallback_password'] = $fallback_password;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int|null
     */
    public function getPriority(): ?int
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int|null $priority The priority of this call over other calls from your account.
     *
     * @return $this
     */
    public function setPriority(?int $priority): static
    {
        if (is_null($priority)) {
            array_push($this->openAPINullablesSetToNull, 'priority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('priority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['priority'] = $priority;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


