<?php
/**
 * CreateCall
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bandwidth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Bandwidth\ObjectSerializer;

/**
 * CreateCall Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateCall implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'createCall';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'to' => 'string',
        'from' => 'string',
        'privacy' => 'bool',
        'display_name' => 'string',
        'uui' => 'string',
        'application_id' => 'string',
        'answer_url' => 'string',
        'answer_method' => '\Bandwidth\Model\CallbackMethodEnum',
        'username' => 'string',
        'password' => 'string',
        'answer_fallback_url' => 'string',
        'answer_fallback_method' => '\Bandwidth\Model\CallbackMethodEnum',
        'fallback_username' => 'string',
        'fallback_password' => 'string',
        'disconnect_url' => 'string',
        'disconnect_method' => '\Bandwidth\Model\CallbackMethodEnum',
        'call_timeout' => 'float',
        'callback_timeout' => 'float',
        'machine_detection' => '\Bandwidth\Model\MachineDetectionConfiguration',
        'priority' => 'int',
        'tag' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'to' => null,
        'from' => null,
        'privacy' => null,
        'display_name' => null,
        'uui' => null,
        'application_id' => null,
        'answer_url' => 'uri',
        'answer_method' => null,
        'username' => null,
        'password' => null,
        'answer_fallback_url' => 'uri',
        'answer_fallback_method' => null,
        'fallback_username' => null,
        'fallback_password' => null,
        'disconnect_url' => 'uri',
        'disconnect_method' => null,
        'call_timeout' => 'double',
        'callback_timeout' => 'double',
        'machine_detection' => null,
        'priority' => null,
        'tag' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'to' => false,
        'from' => false,
        'privacy' => true,
        'display_name' => true,
        'uui' => true,
        'application_id' => false,
        'answer_url' => false,
        'answer_method' => true,
        'username' => true,
        'password' => true,
        'answer_fallback_url' => true,
        'answer_fallback_method' => true,
        'fallback_username' => true,
        'fallback_password' => true,
        'disconnect_url' => true,
        'disconnect_method' => true,
        'call_timeout' => true,
        'callback_timeout' => true,
        'machine_detection' => false,
        'priority' => true,
        'tag' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'to' => 'to',
        'from' => 'from',
        'privacy' => 'privacy',
        'display_name' => 'displayName',
        'uui' => 'uui',
        'application_id' => 'applicationId',
        'answer_url' => 'answerUrl',
        'answer_method' => 'answerMethod',
        'username' => 'username',
        'password' => 'password',
        'answer_fallback_url' => 'answerFallbackUrl',
        'answer_fallback_method' => 'answerFallbackMethod',
        'fallback_username' => 'fallbackUsername',
        'fallback_password' => 'fallbackPassword',
        'disconnect_url' => 'disconnectUrl',
        'disconnect_method' => 'disconnectMethod',
        'call_timeout' => 'callTimeout',
        'callback_timeout' => 'callbackTimeout',
        'machine_detection' => 'machineDetection',
        'priority' => 'priority',
        'tag' => 'tag'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'to' => 'setTo',
        'from' => 'setFrom',
        'privacy' => 'setPrivacy',
        'display_name' => 'setDisplayName',
        'uui' => 'setUui',
        'application_id' => 'setApplicationId',
        'answer_url' => 'setAnswerUrl',
        'answer_method' => 'setAnswerMethod',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'answer_fallback_url' => 'setAnswerFallbackUrl',
        'answer_fallback_method' => 'setAnswerFallbackMethod',
        'fallback_username' => 'setFallbackUsername',
        'fallback_password' => 'setFallbackPassword',
        'disconnect_url' => 'setDisconnectUrl',
        'disconnect_method' => 'setDisconnectMethod',
        'call_timeout' => 'setCallTimeout',
        'callback_timeout' => 'setCallbackTimeout',
        'machine_detection' => 'setMachineDetection',
        'priority' => 'setPriority',
        'tag' => 'setTag'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'to' => 'getTo',
        'from' => 'getFrom',
        'privacy' => 'getPrivacy',
        'display_name' => 'getDisplayName',
        'uui' => 'getUui',
        'application_id' => 'getApplicationId',
        'answer_url' => 'getAnswerUrl',
        'answer_method' => 'getAnswerMethod',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'answer_fallback_url' => 'getAnswerFallbackUrl',
        'answer_fallback_method' => 'getAnswerFallbackMethod',
        'fallback_username' => 'getFallbackUsername',
        'fallback_password' => 'getFallbackPassword',
        'disconnect_url' => 'getDisconnectUrl',
        'disconnect_method' => 'getDisconnectMethod',
        'call_timeout' => 'getCallTimeout',
        'callback_timeout' => 'getCallbackTimeout',
        'machine_detection' => 'getMachineDetection',
        'priority' => 'getPriority',
        'tag' => 'getTag'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('privacy', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('uui', $data ?? [], null);
        $this->setIfExists('application_id', $data ?? [], null);
        $this->setIfExists('answer_url', $data ?? [], null);
        $this->setIfExists('answer_method', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('answer_fallback_url', $data ?? [], null);
        $this->setIfExists('answer_fallback_method', $data ?? [], null);
        $this->setIfExists('fallback_username', $data ?? [], null);
        $this->setIfExists('fallback_password', $data ?? [], null);
        $this->setIfExists('disconnect_url', $data ?? [], null);
        $this->setIfExists('disconnect_method', $data ?? [], null);
        $this->setIfExists('call_timeout', $data ?? [], 30);
        $this->setIfExists('callback_timeout', $data ?? [], 15);
        $this->setIfExists('machine_detection', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], 5);
        $this->setIfExists('tag', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if (!is_null($this->container['display_name']) && (mb_strlen($this->container['display_name']) > 256)) {
            $invalidProperties[] = "invalid value for 'display_name', the character length must be smaller than or equal to 256.";
        }

        if ($this->container['application_id'] === null) {
            $invalidProperties[] = "'application_id' can't be null";
        }
        if ($this->container['answer_url'] === null) {
            $invalidProperties[] = "'answer_url' can't be null";
        }
        if (!is_null($this->container['answer_url']) && (mb_strlen($this->container['answer_url']) > 2048)) {
            $invalidProperties[] = "invalid value for 'answer_url', the character length must be smaller than or equal to 2048.";
        }

        if (!is_null($this->container['username']) && (mb_strlen($this->container['username']) > 1024)) {
            $invalidProperties[] = "invalid value for 'username', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['password']) && (mb_strlen($this->container['password']) > 1024)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['answer_fallback_url']) && (mb_strlen($this->container['answer_fallback_url']) > 2048)) {
            $invalidProperties[] = "invalid value for 'answer_fallback_url', the character length must be smaller than or equal to 2048.";
        }

        if (!is_null($this->container['fallback_username']) && (mb_strlen($this->container['fallback_username']) > 1024)) {
            $invalidProperties[] = "invalid value for 'fallback_username', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['fallback_password']) && (mb_strlen($this->container['fallback_password']) > 1024)) {
            $invalidProperties[] = "invalid value for 'fallback_password', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['disconnect_url']) && (mb_strlen($this->container['disconnect_url']) > 2048)) {
            $invalidProperties[] = "invalid value for 'disconnect_url', the character length must be smaller than or equal to 2048.";
        }

        if (!is_null($this->container['call_timeout']) && ($this->container['call_timeout'] > 300)) {
            $invalidProperties[] = "invalid value for 'call_timeout', must be smaller than or equal to 300.";
        }

        if (!is_null($this->container['call_timeout']) && ($this->container['call_timeout'] < 1)) {
            $invalidProperties[] = "invalid value for 'call_timeout', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['callback_timeout']) && ($this->container['callback_timeout'] > 25)) {
            $invalidProperties[] = "invalid value for 'callback_timeout', must be smaller than or equal to 25.";
        }

        if (!is_null($this->container['callback_timeout']) && ($this->container['callback_timeout'] < 1)) {
            $invalidProperties[] = "invalid value for 'callback_timeout', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['priority']) && ($this->container['priority'] > 5)) {
            $invalidProperties[] = "invalid value for 'priority', must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['priority']) && ($this->container['priority'] < 1)) {
            $invalidProperties[] = "invalid value for 'priority', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['tag']) && (mb_strlen($this->container['tag']) > 4096)) {
            $invalidProperties[] = "invalid value for 'tag', the character length must be smaller than or equal to 4096.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets to
     *
     * @return string
     */
    public function getTo(): string
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string $to The destination to call (must be an E.164 formatted number (e.g. `+15555551212`) or a SIP URI (e.g. `sip:user@server.example`)).
     *
     * @return $this
     */
    public function setTo(string $to): static
    {
        if (is_null($to)) {
            throw new InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom(): string
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from A Bandwidth phone number on your account the call should come from (must be in E.164 format, like `+15555551212`) even if `privacy` is set to true.
     *
     * @return $this
     */
    public function setFrom(string $from): static
    {
        if (is_null($from)) {
            throw new InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets privacy
     *
     * @return bool|null
     */
    public function getPrivacy(): ?bool
    {
        return $this->container['privacy'];
    }

    /**
     * Sets privacy
     *
     * @param bool|null $privacy Hide the calling number. The `displayName` field can be used to customize the displayed name.
     *
     * @return $this
     */
    public function setPrivacy(?bool $privacy): static
    {
        if (is_null($privacy)) {
            array_push($this->openAPINullablesSetToNull, 'privacy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('privacy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['privacy'] = $privacy;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName(): ?string
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name The caller display name to use when the call is created. May not exceed 256 characters nor contain control characters such as new lines. If `privacy` is true, only the following values are valid: `Restricted`, `Anonymous`, `Private`, or `Unavailable`.
     *
     * @return $this
     */
    public function setDisplayName(?string $display_name): static
    {
        if (is_null($display_name)) {
            array_push($this->openAPINullablesSetToNull, 'display_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($display_name) && (mb_strlen($display_name) > 256)) {
            throw new InvalidArgumentException('invalid length for $display_name when calling CreateCall., must be smaller than or equal to 256.');
        }

        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets uui
     *
     * @return string|null
     */
    public function getUui(): ?string
    {
        return $this->container['uui'];
    }

    /**
     * Sets uui
     *
     * @param string|null $uui A comma-separated list of 'User-To-User' headers to be sent in the INVITE when calling a SIP URI. Each value must end with an 'encoding' parameter as described in <a href='https://tools.ietf.org/html/rfc7433'>RFC 7433</a>. Only 'jwt', 'base64' and 'hex' encodings are allowed. The entire value cannot exceed 350 characters, including parameters and separators.
     *
     * @return $this
     */
    public function setUui(?string $uui): static
    {
        if (is_null($uui)) {
            array_push($this->openAPINullablesSetToNull, 'uui');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('uui', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['uui'] = $uui;

        return $this;
    }

    /**
     * Gets application_id
     *
     * @return string
     */
    public function getApplicationId(): string
    {
        return $this->container['application_id'];
    }

    /**
     * Sets application_id
     *
     * @param string $application_id The id of the application associated with the `from` number.
     *
     * @return $this
     */
    public function setApplicationId(string $application_id): static
    {
        if (is_null($application_id)) {
            throw new InvalidArgumentException('non-nullable application_id cannot be null');
        }
        $this->container['application_id'] = $application_id;

        return $this;
    }

    /**
     * Gets answer_url
     *
     * @return string
     */
    public function getAnswerUrl(): string
    {
        return $this->container['answer_url'];
    }

    /**
     * Sets answer_url
     *
     * @param string $answer_url The full URL to send the <a href='/docs/voice/webhooks/answer'>Answer</a> event to when the called party answers. This endpoint should return the first <a href='/docs/voice/bxml'>BXML document</a> to be executed in the call.  Must use `https` if specifying `username` and `password`.
     *
     * @return $this
     */
    public function setAnswerUrl(string $answer_url): static
    {
        if (is_null($answer_url)) {
            throw new InvalidArgumentException('non-nullable answer_url cannot be null');
        }
        if ((mb_strlen($answer_url) > 2048)) {
            throw new InvalidArgumentException('invalid length for $answer_url when calling CreateCall., must be smaller than or equal to 2048.');
        }

        $this->container['answer_url'] = $answer_url;

        return $this;
    }

    /**
     * Gets answer_method
     *
     * @return \Bandwidth\Model\CallbackMethodEnum|null
     */
    public function getAnswerMethod(): ?\Bandwidth\Model\CallbackMethodEnum
    {
        return $this->container['answer_method'];
    }

    /**
     * Sets answer_method
     *
     * @param \Bandwidth\Model\CallbackMethodEnum|null $answer_method answer_method
     *
     * @return $this
     */
    public function setAnswerMethod(?\Bandwidth\Model\CallbackMethodEnum $answer_method): static
    {
        if (is_null($answer_method)) {
            array_push($this->openAPINullablesSetToNull, 'answer_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['answer_method'] = $answer_method;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username Basic auth username.
     *
     * @return $this
     */
    public function setUsername(?string $username): static
    {
        if (is_null($username)) {
            array_push($this->openAPINullablesSetToNull, 'username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($username) && (mb_strlen($username) > 1024)) {
            throw new InvalidArgumentException('invalid length for $username when calling CreateCall., must be smaller than or equal to 1024.');
        }

        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password Basic auth password.
     *
     * @return $this
     */
    public function setPassword(?string $password): static
    {
        if (is_null($password)) {
            array_push($this->openAPINullablesSetToNull, 'password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($password) && (mb_strlen($password) > 1024)) {
            throw new InvalidArgumentException('invalid length for $password when calling CreateCall., must be smaller than or equal to 1024.');
        }

        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets answer_fallback_url
     *
     * @return string|null
     */
    public function getAnswerFallbackUrl(): ?string
    {
        return $this->container['answer_fallback_url'];
    }

    /**
     * Sets answer_fallback_url
     *
     * @param string|null $answer_fallback_url A fallback url which, if provided, will be used to retry the `answer` webhook delivery in case `answerUrl` fails to respond  Must use `https` if specifying `fallbackUsername` and `fallbackPassword`.
     *
     * @return $this
     */
    public function setAnswerFallbackUrl(?string $answer_fallback_url): static
    {
        if (is_null($answer_fallback_url)) {
            array_push($this->openAPINullablesSetToNull, 'answer_fallback_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_fallback_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($answer_fallback_url) && (mb_strlen($answer_fallback_url) > 2048)) {
            throw new InvalidArgumentException('invalid length for $answer_fallback_url when calling CreateCall., must be smaller than or equal to 2048.');
        }

        $this->container['answer_fallback_url'] = $answer_fallback_url;

        return $this;
    }

    /**
     * Gets answer_fallback_method
     *
     * @return \Bandwidth\Model\CallbackMethodEnum|null
     */
    public function getAnswerFallbackMethod(): ?\Bandwidth\Model\CallbackMethodEnum
    {
        return $this->container['answer_fallback_method'];
    }

    /**
     * Sets answer_fallback_method
     *
     * @param \Bandwidth\Model\CallbackMethodEnum|null $answer_fallback_method answer_fallback_method
     *
     * @return $this
     */
    public function setAnswerFallbackMethod(?\Bandwidth\Model\CallbackMethodEnum $answer_fallback_method): static
    {
        if (is_null($answer_fallback_method)) {
            array_push($this->openAPINullablesSetToNull, 'answer_fallback_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_fallback_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['answer_fallback_method'] = $answer_fallback_method;

        return $this;
    }

    /**
     * Gets fallback_username
     *
     * @return string|null
     */
    public function getFallbackUsername(): ?string
    {
        return $this->container['fallback_username'];
    }

    /**
     * Sets fallback_username
     *
     * @param string|null $fallback_username Basic auth username.
     *
     * @return $this
     */
    public function setFallbackUsername(?string $fallback_username): static
    {
        if (is_null($fallback_username)) {
            array_push($this->openAPINullablesSetToNull, 'fallback_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fallback_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($fallback_username) && (mb_strlen($fallback_username) > 1024)) {
            throw new InvalidArgumentException('invalid length for $fallback_username when calling CreateCall., must be smaller than or equal to 1024.');
        }

        $this->container['fallback_username'] = $fallback_username;

        return $this;
    }

    /**
     * Gets fallback_password
     *
     * @return string|null
     */
    public function getFallbackPassword(): ?string
    {
        return $this->container['fallback_password'];
    }

    /**
     * Sets fallback_password
     *
     * @param string|null $fallback_password Basic auth password.
     *
     * @return $this
     */
    public function setFallbackPassword(?string $fallback_password): static
    {
        if (is_null($fallback_password)) {
            array_push($this->openAPINullablesSetToNull, 'fallback_password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fallback_password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($fallback_password) && (mb_strlen($fallback_password) > 1024)) {
            throw new InvalidArgumentException('invalid length for $fallback_password when calling CreateCall., must be smaller than or equal to 1024.');
        }

        $this->container['fallback_password'] = $fallback_password;

        return $this;
    }

    /**
     * Gets disconnect_url
     *
     * @return string|null
     */
    public function getDisconnectUrl(): ?string
    {
        return $this->container['disconnect_url'];
    }

    /**
     * Sets disconnect_url
     *
     * @param string|null $disconnect_url The URL to send the <a href='/docs/voice/webhooks/disconnect'>Disconnect</a> event to when the call ends. This event does not expect a BXML response.
     *
     * @return $this
     */
    public function setDisconnectUrl(?string $disconnect_url): static
    {
        if (is_null($disconnect_url)) {
            array_push($this->openAPINullablesSetToNull, 'disconnect_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disconnect_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($disconnect_url) && (mb_strlen($disconnect_url) > 2048)) {
            throw new InvalidArgumentException('invalid length for $disconnect_url when calling CreateCall., must be smaller than or equal to 2048.');
        }

        $this->container['disconnect_url'] = $disconnect_url;

        return $this;
    }

    /**
     * Gets disconnect_method
     *
     * @return \Bandwidth\Model\CallbackMethodEnum|null
     */
    public function getDisconnectMethod(): ?\Bandwidth\Model\CallbackMethodEnum
    {
        return $this->container['disconnect_method'];
    }

    /**
     * Sets disconnect_method
     *
     * @param \Bandwidth\Model\CallbackMethodEnum|null $disconnect_method disconnect_method
     *
     * @return $this
     */
    public function setDisconnectMethod(?\Bandwidth\Model\CallbackMethodEnum $disconnect_method): static
    {
        if (is_null($disconnect_method)) {
            array_push($this->openAPINullablesSetToNull, 'disconnect_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disconnect_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disconnect_method'] = $disconnect_method;

        return $this;
    }

    /**
     * Gets call_timeout
     *
     * @return float|null
     */
    public function getCallTimeout(): ?float
    {
        return $this->container['call_timeout'];
    }

    /**
     * Sets call_timeout
     *
     * @param float|null $call_timeout The timeout (in seconds) for the callee to answer the call after it starts ringing. If the call does not start ringing within 30s, the call will be cancelled regardless of this value.  Can be any numeric value (including decimals) between 1 and 300.
     *
     * @return $this
     */
    public function setCallTimeout(?float $call_timeout): static
    {
        if (is_null($call_timeout)) {
            array_push($this->openAPINullablesSetToNull, 'call_timeout');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('call_timeout', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($call_timeout) && ($call_timeout > 300)) {
            throw new InvalidArgumentException('invalid value for $call_timeout when calling CreateCall., must be smaller than or equal to 300.');
        }
        if (!is_null($call_timeout) && ($call_timeout < 1)) {
            throw new InvalidArgumentException('invalid value for $call_timeout when calling CreateCall., must be bigger than or equal to 1.');
        }

        $this->container['call_timeout'] = $call_timeout;

        return $this;
    }

    /**
     * Gets callback_timeout
     *
     * @return float|null
     */
    public function getCallbackTimeout(): ?float
    {
        return $this->container['callback_timeout'];
    }

    /**
     * Sets callback_timeout
     *
     * @param float|null $callback_timeout This is the timeout (in seconds) to use when delivering webhooks for the call. Can be any numeric value (including decimals) between 1 and 25.
     *
     * @return $this
     */
    public function setCallbackTimeout(?float $callback_timeout): static
    {
        if (is_null($callback_timeout)) {
            array_push($this->openAPINullablesSetToNull, 'callback_timeout');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('callback_timeout', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($callback_timeout) && ($callback_timeout > 25)) {
            throw new InvalidArgumentException('invalid value for $callback_timeout when calling CreateCall., must be smaller than or equal to 25.');
        }
        if (!is_null($callback_timeout) && ($callback_timeout < 1)) {
            throw new InvalidArgumentException('invalid value for $callback_timeout when calling CreateCall., must be bigger than or equal to 1.');
        }

        $this->container['callback_timeout'] = $callback_timeout;

        return $this;
    }

    /**
     * Gets machine_detection
     *
     * @return \Bandwidth\Model\MachineDetectionConfiguration|null
     */
    public function getMachineDetection(): ?\Bandwidth\Model\MachineDetectionConfiguration
    {
        return $this->container['machine_detection'];
    }

    /**
     * Sets machine_detection
     *
     * @param \Bandwidth\Model\MachineDetectionConfiguration|null $machine_detection machine_detection
     *
     * @return $this
     */
    public function setMachineDetection(?\Bandwidth\Model\MachineDetectionConfiguration $machine_detection): static
    {
        if (is_null($machine_detection)) {
            throw new InvalidArgumentException('non-nullable machine_detection cannot be null');
        }
        $this->container['machine_detection'] = $machine_detection;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int|null
     */
    public function getPriority(): ?int
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int|null $priority The priority of this call over other calls from your account. For example, if during a call your application needs to place a new call and bridge it with the current call, you might want to create the call with priority 1 so that it will be the next call picked off your queue, ahead of other less time sensitive calls. A lower value means higher priority, so a priority 1 call takes precedence over a priority 2 call.
     *
     * @return $this
     */
    public function setPriority(?int $priority): static
    {
        if (is_null($priority)) {
            array_push($this->openAPINullablesSetToNull, 'priority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('priority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($priority) && ($priority > 5)) {
            throw new InvalidArgumentException('invalid value for $priority when calling CreateCall., must be smaller than or equal to 5.');
        }
        if (!is_null($priority) && ($priority < 1)) {
            throw new InvalidArgumentException('invalid value for $priority when calling CreateCall., must be bigger than or equal to 1.');
        }

        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string|null
     */
    public function getTag(): ?string
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string|null $tag A custom string that will be sent with all webhooks for this call unless overwritten by a future <a href='/docs/voice/bxml/tag'>`<Tag>`</a> verb or `tag` attribute on another verb, or cleared.  May be cleared by setting `tag=\"\"`  Max length 4096 characters.
     *
     * @return $this
     */
    public function setTag(?string $tag): static
    {
        if (is_null($tag)) {
            array_push($this->openAPINullablesSetToNull, 'tag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($tag) && (mb_strlen($tag) > 4096)) {
            throw new InvalidArgumentException('invalid length for $tag when calling CreateCall., must be smaller than or equal to 4096.');
        }

        $this->container['tag'] = $tag;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


