<?php
/**
 * CreateWebRtcConnectionRequest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bandwidth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Bandwidth\ObjectSerializer;

/**
 * CreateWebRtcConnectionRequest Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateWebRtcConnectionRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'createWebRtcConnectionRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'type' => '\Bandwidth\Model\EndpointTypeEnum',
        'direction' => '\Bandwidth\Model\EndpointDirectionEnum',
        'event_callback_url' => 'string',
        'event_fallback_url' => 'string',
        'tag' => 'string',
        'connection_metadata' => 'object'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'type' => null,
        'direction' => null,
        'event_callback_url' => 'uri',
        'event_fallback_url' => 'uri',
        'tag' => null,
        'connection_metadata' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'type' => false,
        'direction' => false,
        'event_callback_url' => false,
        'event_fallback_url' => false,
        'tag' => false,
        'connection_metadata' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'type' => 'type',
        'direction' => 'direction',
        'event_callback_url' => 'eventCallbackUrl',
        'event_fallback_url' => 'eventFallbackUrl',
        'tag' => 'tag',
        'connection_metadata' => 'connectionMetadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'type' => 'setType',
        'direction' => 'setDirection',
        'event_callback_url' => 'setEventCallbackUrl',
        'event_fallback_url' => 'setEventFallbackUrl',
        'tag' => 'setTag',
        'connection_metadata' => 'setConnectionMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'type' => 'getType',
        'direction' => 'getDirection',
        'event_callback_url' => 'getEventCallbackUrl',
        'event_fallback_url' => 'getEventFallbackUrl',
        'tag' => 'getTag',
        'connection_metadata' => 'getConnectionMetadata'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('direction', $data ?? [], null);
        $this->setIfExists('event_callback_url', $data ?? [], null);
        $this->setIfExists('event_fallback_url', $data ?? [], null);
        $this->setIfExists('tag', $data ?? [], null);
        $this->setIfExists('connection_metadata', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['direction'] === null) {
            $invalidProperties[] = "'direction' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return \Bandwidth\Model\EndpointTypeEnum
     */
    public function getType(): \Bandwidth\Model\EndpointTypeEnum
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Bandwidth\Model\EndpointTypeEnum $type type
     *
     * @return $this
     */
    public function setType(\Bandwidth\Model\EndpointTypeEnum $type): static
    {
        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets direction
     *
     * @return \Bandwidth\Model\EndpointDirectionEnum
     */
    public function getDirection(): \Bandwidth\Model\EndpointDirectionEnum
    {
        return $this->container['direction'];
    }

    /**
     * Sets direction
     *
     * @param \Bandwidth\Model\EndpointDirectionEnum $direction direction
     *
     * @return $this
     */
    public function setDirection(\Bandwidth\Model\EndpointDirectionEnum $direction): static
    {
        if (is_null($direction)) {
            throw new InvalidArgumentException('non-nullable direction cannot be null');
        }
        $this->container['direction'] = $direction;

        return $this;
    }

    /**
     * Gets event_callback_url
     *
     * @return string|null
     */
    public function getEventCallbackUrl(): ?string
    {
        return $this->container['event_callback_url'];
    }

    /**
     * Sets event_callback_url
     *
     * @param string|null $event_callback_url The URL to send event callbacks to.
     *
     * @return $this
     */
    public function setEventCallbackUrl(?string $event_callback_url): static
    {
        if (is_null($event_callback_url)) {
            throw new InvalidArgumentException('non-nullable event_callback_url cannot be null');
        }
        $this->container['event_callback_url'] = $event_callback_url;

        return $this;
    }

    /**
     * Gets event_fallback_url
     *
     * @return string|null
     */
    public function getEventFallbackUrl(): ?string
    {
        return $this->container['event_fallback_url'];
    }

    /**
     * Sets event_fallback_url
     *
     * @param string|null $event_fallback_url The URL to send event fallbacks to.
     *
     * @return $this
     */
    public function setEventFallbackUrl(?string $event_fallback_url): static
    {
        if (is_null($event_fallback_url)) {
            throw new InvalidArgumentException('non-nullable event_fallback_url cannot be null');
        }
        $this->container['event_fallback_url'] = $event_fallback_url;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string|null
     */
    public function getTag(): ?string
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string|null $tag A tag for the endpoint.
     *
     * @return $this
     */
    public function setTag(?string $tag): static
    {
        if (is_null($tag)) {
            throw new InvalidArgumentException('non-nullable tag cannot be null');
        }


        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets connection_metadata
     *
     * @return object|null
     */
    public function getConnectionMetadata(): ?object
    {
        return $this->container['connection_metadata'];
    }

    /**
     * Sets connection_metadata
     *
     * @param object|null $connection_metadata connection_metadata
     *
     * @return $this
     */
    public function setConnectionMetadata(?object $connection_metadata): static
    {
        if (is_null($connection_metadata)) {
            throw new InvalidArgumentException('non-nullable connection_metadata cannot be null');
        }
        $this->container['connection_metadata'] = $connection_metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


