<?php
/**
 * LineTypeEnum
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bandwidth\Model;

/**
 * LineTypeEnum Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum LineTypeEnum: string
{
    case FIXED = 'FIXED';

    case VOIP_FIXED = 'VOIP-FIXED';

    case MOBILE = 'MOBILE';

    case VOIP = 'VOIP';
}


