<?php
/**
 * MultiChannelChannelListRBMObjectAllOfContent
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bandwidth\Model;

/**
 * MultiChannelChannelListRBMObjectAllOfContent Class Doc Comment
 *
 * @description The content of the message.
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MultiChannelChannelListRBMObjectAllOfContent implements ComposedInterface
{
    /**
     * The original name of the model.
     *
     * @var string
     */
    public const MODEL_NAME = 'multiChannelChannelListRBMObject_allOf_content';

    /**
     * The discriminator property name, or null when the schema has no discriminator.
     *
     * @var string|null
     */
    public const DISCRIMINATOR = null;

    /**
     * {@inheritdoc}
     */
    public static function getComposedTypes(): array
    {
        return [
            '\Bandwidth\Model\RbmMessageContentText',
            '\Bandwidth\Model\RbmMessageMedia',
            '\Bandwidth\Model\RbmMessageContentRichCard'
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function getComposedDiscriminator(): ?string
    {
        return self::DISCRIMINATOR;
    }

    /**
     * {@inheritdoc}
     */
    public static function getComposedDiscriminatorMappings(): array
    {
        return [
            
        ];
    }
}


