<?php
/**
 * RbmMessageContentRichCard
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bandwidth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Bandwidth\ObjectSerializer;

/**
 * RbmMessageContentRichCard Class Doc Comment
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class RbmMessageContentRichCard implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'rbmMessageContentRichCard';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'orientation' => '\Bandwidth\Model\StandaloneCardOrientationEnum',
        'thumbnail_image_alignment' => '\Bandwidth\Model\ThumbnailAlignmentEnum',
        'card_content' => '\Bandwidth\Model\RbmCardContent',
        'suggestions' => '\Bandwidth\Model\MultiChannelAction[]',
        'card_width' => '\Bandwidth\Model\CardWidthEnum',
        'card_contents' => '\Bandwidth\Model\RbmCardContent[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'orientation' => null,
        'thumbnail_image_alignment' => null,
        'card_content' => null,
        'suggestions' => null,
        'card_width' => null,
        'card_contents' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'orientation' => false,
        'thumbnail_image_alignment' => false,
        'card_content' => false,
        'suggestions' => false,
        'card_width' => false,
        'card_contents' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'orientation' => 'orientation',
        'thumbnail_image_alignment' => 'thumbnailImageAlignment',
        'card_content' => 'cardContent',
        'suggestions' => 'suggestions',
        'card_width' => 'cardWidth',
        'card_contents' => 'cardContents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'orientation' => 'setOrientation',
        'thumbnail_image_alignment' => 'setThumbnailImageAlignment',
        'card_content' => 'setCardContent',
        'suggestions' => 'setSuggestions',
        'card_width' => 'setCardWidth',
        'card_contents' => 'setCardContents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'orientation' => 'getOrientation',
        'thumbnail_image_alignment' => 'getThumbnailImageAlignment',
        'card_content' => 'getCardContent',
        'suggestions' => 'getSuggestions',
        'card_width' => 'getCardWidth',
        'card_contents' => 'getCardContents'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('orientation', $data ?? [], null);
        $this->setIfExists('thumbnail_image_alignment', $data ?? [], null);
        $this->setIfExists('card_content', $data ?? [], null);
        $this->setIfExists('suggestions', $data ?? [], null);
        $this->setIfExists('card_width', $data ?? [], null);
        $this->setIfExists('card_contents', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['orientation'] === null) {
            $invalidProperties[] = "'orientation' can't be null";
        }
        if ($this->container['card_content'] === null) {
            $invalidProperties[] = "'card_content' can't be null";
        }
        if (!is_null($this->container['suggestions']) && (count($this->container['suggestions']) > 11)) {
            $invalidProperties[] = "invalid value for 'suggestions', number of items must be less than or equal to 11.";
        }

        if ($this->container['card_width'] === null) {
            $invalidProperties[] = "'card_width' can't be null";
        }
        if ($this->container['card_contents'] === null) {
            $invalidProperties[] = "'card_contents' can't be null";
        }
        if ((count($this->container['card_contents']) > 10)) {
            $invalidProperties[] = "invalid value for 'card_contents', number of items must be less than or equal to 10.";
        }

        if ((count($this->container['card_contents']) < 2)) {
            $invalidProperties[] = "invalid value for 'card_contents', number of items must be greater than or equal to 2.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets orientation
     *
     * @return \Bandwidth\Model\StandaloneCardOrientationEnum
     */
    public function getOrientation(): \Bandwidth\Model\StandaloneCardOrientationEnum
    {
        return $this->container['orientation'];
    }

    /**
     * Sets orientation
     *
     * @param \Bandwidth\Model\StandaloneCardOrientationEnum $orientation orientation
     *
     * @return $this
     */
    public function setOrientation(\Bandwidth\Model\StandaloneCardOrientationEnum $orientation): static
    {
        if (is_null($orientation)) {
            throw new InvalidArgumentException('non-nullable orientation cannot be null');
        }
        $this->container['orientation'] = $orientation;

        return $this;
    }

    /**
     * Gets thumbnail_image_alignment
     *
     * @return \Bandwidth\Model\ThumbnailAlignmentEnum|null
     */
    public function getThumbnailImageAlignment(): ?\Bandwidth\Model\ThumbnailAlignmentEnum
    {
        return $this->container['thumbnail_image_alignment'];
    }

    /**
     * Sets thumbnail_image_alignment
     *
     * @param \Bandwidth\Model\ThumbnailAlignmentEnum|null $thumbnail_image_alignment thumbnail_image_alignment
     *
     * @return $this
     */
    public function setThumbnailImageAlignment(?\Bandwidth\Model\ThumbnailAlignmentEnum $thumbnail_image_alignment): static
    {
        if (is_null($thumbnail_image_alignment)) {
            throw new InvalidArgumentException('non-nullable thumbnail_image_alignment cannot be null');
        }
        $this->container['thumbnail_image_alignment'] = $thumbnail_image_alignment;

        return $this;
    }

    /**
     * Gets card_content
     *
     * @return \Bandwidth\Model\RbmCardContent
     */
    public function getCardContent(): \Bandwidth\Model\RbmCardContent
    {
        return $this->container['card_content'];
    }

    /**
     * Sets card_content
     *
     * @param \Bandwidth\Model\RbmCardContent $card_content card_content
     *
     * @return $this
     */
    public function setCardContent(\Bandwidth\Model\RbmCardContent $card_content): static
    {
        if (is_null($card_content)) {
            throw new InvalidArgumentException('non-nullable card_content cannot be null');
        }
        $this->container['card_content'] = $card_content;

        return $this;
    }

    /**
     * Gets suggestions
     *
     * @return \Bandwidth\Model\MultiChannelAction[]|null
     */
    public function getSuggestions(): ?array
    {
        return $this->container['suggestions'];
    }

    /**
     * Sets suggestions
     *
     * @param \Bandwidth\Model\MultiChannelAction[]|null $suggestions An array of suggested actions for the recipient.
     *
     * @return $this
     */
    public function setSuggestions(?array $suggestions): static
    {
        if (is_null($suggestions)) {
            throw new InvalidArgumentException('non-nullable suggestions cannot be null');
        }

        if ((count($suggestions) > 11)) {
            throw new InvalidArgumentException('invalid value for $suggestions when calling RbmMessageContentRichCard., number of items must be less than or equal to 11.');
        }
        $this->container['suggestions'] = $suggestions;

        return $this;
    }

    /**
     * Gets card_width
     *
     * @return \Bandwidth\Model\CardWidthEnum
     */
    public function getCardWidth(): \Bandwidth\Model\CardWidthEnum
    {
        return $this->container['card_width'];
    }

    /**
     * Sets card_width
     *
     * @param \Bandwidth\Model\CardWidthEnum $card_width card_width
     *
     * @return $this
     */
    public function setCardWidth(\Bandwidth\Model\CardWidthEnum $card_width): static
    {
        if (is_null($card_width)) {
            throw new InvalidArgumentException('non-nullable card_width cannot be null');
        }
        $this->container['card_width'] = $card_width;

        return $this;
    }

    /**
     * Gets card_contents
     *
     * @return \Bandwidth\Model\RbmCardContent[]
     */
    public function getCardContents(): array
    {
        return $this->container['card_contents'];
    }

    /**
     * Sets card_contents
     *
     * @param \Bandwidth\Model\RbmCardContent[] $card_contents card_contents
     *
     * @return $this
     */
    public function setCardContents(array $card_contents): static
    {
        if (is_null($card_contents)) {
            throw new InvalidArgumentException('non-nullable card_contents cannot be null');
        }

        if ((count($card_contents) > 10)) {
            throw new InvalidArgumentException('invalid value for $card_contents when calling RbmMessageContentRichCard., number of items must be less than or equal to 10.');
        }
        if ((count($card_contents) < 2)) {
            throw new InvalidArgumentException('invalid length for $card_contents when calling RbmMessageContentRichCard., number of items must be greater than or equal to 2.');
        }
        $this->container['card_contents'] = $card_contents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


