<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\WebRtc\Models;

/**
 * The type of media the participant is allowed to publish
 *
 * VIDEO permission implies AUDIO permission as well
 */
class MediaTypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const AUDIO = "AUDIO";

    /**
     * TODO: Write general description for this element
     */
    const VIDEO = "VIDEO";
}
