<?php

declare(strict_types=1);

/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\WebRtc\Models;

class ParticipantSubscription implements \JsonSerializable
{
    /**
     * @var string
     */
    private $participantId;

    /**
     * @param string $participantId
     */
    public function __construct(string $participantId)
    {
        $this->participantId = $participantId;
    }

    /**
     * Returns Participant Id.
     *
     * Participant the subscriber should be subscribed to
     */
    public function getParticipantId(): string
    {
        return $this->participantId;
    }

    /**
     * Sets Participant Id.
     *
     * Participant the subscriber should be subscribed to
     *
     * @required
     * @maps participantId
     */
    public function setParticipantId(string $participantId): void
    {
        $this->participantId = $participantId;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['participantId'] = $this->participantId;

        return array_filter($json, function ($val) {
            return $val !== null;
        });
    }
}
