<?php

declare(strict_types=1);

/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

class FileFormatEnum
{
    public const MP3 = 'mp3';

    public const WAV = 'wav';
}
