<?php

declare(strict_types=1);

/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

class ModifyConferenceRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $redirectUrl;

    /**
     * @var string|null
     */
    private $redirectFallbackUrl;

    /**
     * @var string|null
     */
    private $redirectMethod;

    /**
     * @var string|null
     */
    private $redirectFallbackMethod;

    /**
     * @var string|null
     */
    private $username;

    /**
     * @var string|null
     */
    private $password;

    /**
     * @var string|null
     */
    private $fallbackUsername;

    /**
     * @var string|null
     */
    private $fallbackPassword;

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Redirect Url.
     */
    public function getRedirectUrl(): ?string
    {
        return $this->redirectUrl;
    }

    /**
     * Sets Redirect Url.
     *
     * @maps redirectUrl
     */
    public function setRedirectUrl(?string $redirectUrl): void
    {
        $this->redirectUrl = $redirectUrl;
    }

    /**
     * Returns Redirect Fallback Url.
     */
    public function getRedirectFallbackUrl(): ?string
    {
        return $this->redirectFallbackUrl;
    }

    /**
     * Sets Redirect Fallback Url.
     *
     * @maps redirectFallbackUrl
     */
    public function setRedirectFallbackUrl(?string $redirectFallbackUrl): void
    {
        $this->redirectFallbackUrl = $redirectFallbackUrl;
    }

    /**
     * Returns Redirect Method.
     */
    public function getRedirectMethod(): ?string
    {
        return $this->redirectMethod;
    }

    /**
     * Sets Redirect Method.
     *
     * @maps redirectMethod
     */
    public function setRedirectMethod(?string $redirectMethod): void
    {
        $this->redirectMethod = $redirectMethod;
    }

    /**
     * Returns Redirect Fallback Method.
     */
    public function getRedirectFallbackMethod(): ?string
    {
        return $this->redirectFallbackMethod;
    }

    /**
     * Sets Redirect Fallback Method.
     *
     * @maps redirectFallbackMethod
     */
    public function setRedirectFallbackMethod(?string $redirectFallbackMethod): void
    {
        $this->redirectFallbackMethod = $redirectFallbackMethod;
    }

    /**
     * Returns Username.
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * Sets Username.
     *
     * @maps username
     */
    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }

    /**
     * Returns Password.
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Sets Password.
     *
     * @maps password
     */
    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    /**
     * Returns Fallback Username.
     */
    public function getFallbackUsername(): ?string
    {
        return $this->fallbackUsername;
    }

    /**
     * Sets Fallback Username.
     *
     * @maps fallbackUsername
     */
    public function setFallbackUsername(?string $fallbackUsername): void
    {
        $this->fallbackUsername = $fallbackUsername;
    }

    /**
     * Returns Fallback Password.
     */
    public function getFallbackPassword(): ?string
    {
        return $this->fallbackPassword;
    }

    /**
     * Sets Fallback Password.
     *
     * @maps fallbackPassword
     */
    public function setFallbackPassword(?string $fallbackPassword): void
    {
        $this->fallbackPassword = $fallbackPassword;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['status']                 = $this->status;
        $json['redirectUrl']            = $this->redirectUrl;
        $json['redirectFallbackUrl']    = $this->redirectFallbackUrl;
        $json['redirectMethod']         = $this->redirectMethod;
        $json['redirectFallbackMethod'] = $this->redirectFallbackMethod;
        $json['username']               = $this->username;
        $json['password']               = $this->password;
        $json['fallbackUsername']       = $this->fallbackUsername;
        $json['fallbackPassword']       = $this->fallbackPassword;

        return array_filter($json, function ($val) {
            return $val !== null;
        });
    }
}
