<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

/**
 * @todo Write general description for this enumeration
 */
class RedirectFallbackMethodEnum
{
    /**
     * TODO: Write general description for this element
     */
    const POST = "POST";

    /**
     * TODO: Write general description for this element
     */
    const GET = "GET";
}
