<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

/**
 * @todo Write general description for this enumeration
 */
class StatusEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ACTIVE = "active";

    /**
     * TODO: Write general description for this element
     */
    const COMPLETED = "completed";
}
