<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

/**
 * @todo Write general description for this enumeration
 */
class State2Enum
{
    /**
     * TODO: Write general description for this element
     */
    const NOT_RECORDING = "NOT_RECORDING";

    /**
     * TODO: Write general description for this element
     */
    const PAUSED = "PAUSED";

    /**
     * TODO: Write general description for this element
     */
    const RECORDING = "RECORDING";
}
