<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

/**
 * @todo Write general description for this enumeration
 */
class Status3Enum
{
    /**
     * TODO: Write general description for this element
     */
    const NONE = "none";

    /**
     * TODO: Write general description for this element
     */
    const PROCESSING = "processing";

    /**
     * TODO: Write general description for this element
     */
    const AVAILABLE = "available";

    /**
     * TODO: Write general description for this element
     */
    const ERROR = "error";

    /**
     * TODO: Write general description for this element
     */
    const TIMEOUT = "timeout";

    /**
     * TODO: Write general description for this element
     */
    const FILESIZETOOBIG = "file-size-too-big";

    /**
     * TODO: Write general description for this element
     */
    const FILESIZETOOSMALL = "file-size-too-small";
}
