<?php

declare(strict_types=1);

/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

class TranscribeRecordingRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $callbackUrl;

    /**
     * @var string|null
     */
    private $callbackMethod;

    /**
     * @var string|null
     */
    private $username;

    /**
     * @var string|null
     */
    private $password;

    /**
     * @var string|null
     */
    private $tag;

    /**
     * @var float|null
     */
    private $callbackTimeout;

    /**
     * Returns Callback Url.
     */
    public function getCallbackUrl(): ?string
    {
        return $this->callbackUrl;
    }

    /**
     * Sets Callback Url.
     *
     * @maps callbackUrl
     */
    public function setCallbackUrl(?string $callbackUrl): void
    {
        $this->callbackUrl = $callbackUrl;
    }

    /**
     * Returns Callback Method.
     */
    public function getCallbackMethod(): ?string
    {
        return $this->callbackMethod;
    }

    /**
     * Sets Callback Method.
     *
     * @maps callbackMethod
     */
    public function setCallbackMethod(?string $callbackMethod): void
    {
        $this->callbackMethod = $callbackMethod;
    }

    /**
     * Returns Username.
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * Sets Username.
     *
     * @maps username
     */
    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }

    /**
     * Returns Password.
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Sets Password.
     *
     * @maps password
     */
    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    /**
     * Returns Tag.
     */
    public function getTag(): ?string
    {
        return $this->tag;
    }

    /**
     * Sets Tag.
     *
     * @maps tag
     */
    public function setTag(?string $tag): void
    {
        $this->tag = $tag;
    }

    /**
     * Returns Callback Timeout.
     */
    public function getCallbackTimeout(): ?float
    {
        return $this->callbackTimeout;
    }

    /**
     * Sets Callback Timeout.
     *
     * @maps callbackTimeout
     */
    public function setCallbackTimeout(?float $callbackTimeout): void
    {
        $this->callbackTimeout = $callbackTimeout;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['callbackUrl']     = $this->callbackUrl;
        $json['callbackMethod']  = $this->callbackMethod;
        $json['username']        = $this->username;
        $json['password']        = $this->password;
        $json['tag']             = $this->tag;
        $json['callbackTimeout'] = $this->callbackTimeout;

        return array_filter($json, function ($val) {
            return $val !== null;
        });
    }
}
