<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\Voice\Models;

/**
 * @todo Write general description for this model
 */
class TranscriptionResponse implements \JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var \BandwidthLib\Voice\Models\Transcript[]|null $transcripts public property
     */
    public $transcripts;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->transcripts = func_get_arg(0);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['transcripts'] = isset($this->transcripts) ?
            array_values($this->transcripts) : null;

        return array_filter($json);
    }
}
