<?php
/**
 * BrtcErrorTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\BrtcError;
use Bandwidth\Model\BrtcErrorSource;

use PHPUnit\Framework\TestCase;

/**
 * BrtcErrorTest Class Doc Comment
 *
 * @description BrtcError
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BrtcErrorTest extends TestCase
{
    private static BrtcError $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new BrtcError([
            'id' => 'test_string',
            'type' => 'test_string',
            'description' => 'test_string',
            'code' => 'test_string',
            'source' => new BrtcErrorSource([])
        ]);
    }

    /**
     * Test "BrtcError"
     */
    public function testBrtcError()
    {
        $this->assertInstanceOf(BrtcError::class, self::$instance);
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertIsString(self::$instance->getId());
        $this->assertEquals('test_string', self::$instance->getId());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertIsString(self::$instance->getType());
        $this->assertEquals('test_string', self::$instance->getType());
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        $this->assertIsString(self::$instance->getDescription());
        $this->assertEquals('test_string', self::$instance->getDescription());
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        $this->assertIsString(self::$instance->getCode());
        $this->assertEquals('test_string', self::$instance->getCode());
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
        $this->assertInstanceOf(BrtcErrorSource::class, self::$instance->getSource());
    }}
