<?php
/**
 * BrtcErrorSourceTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\BrtcErrorSource;

use PHPUnit\Framework\TestCase;

/**
 * BrtcErrorSourceTest Class Doc Comment
 *
 * @description BrtcErrorSource
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BrtcErrorSourceTest extends TestCase
{
    private static BrtcErrorSource $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new BrtcErrorSource([
            'parameter' => 'test_string',
            'field' => 'test_string',
            'header' => 'test_string',
            'reference' => 'test_string'
        ]);
    }

    /**
     * Test "BrtcErrorSource"
     */
    public function testBrtcErrorSource()
    {
        $this->assertInstanceOf(BrtcErrorSource::class, self::$instance);
    }

    /**
     * Test attribute "parameter"
     */
    public function testPropertyParameter()
    {
        $this->assertIsString(self::$instance->getParameter());
        $this->assertEquals('test_string', self::$instance->getParameter());
    }

    /**
     * Test attribute "field"
     */
    public function testPropertyField()
    {
        $this->assertIsString(self::$instance->getField());
        $this->assertEquals('test_string', self::$instance->getField());
    }

    /**
     * Test attribute "header"
     */
    public function testPropertyHeader()
    {
        $this->assertIsString(self::$instance->getHeader());
        $this->assertEquals('test_string', self::$instance->getHeader());
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
        $this->assertIsString(self::$instance->getReference());
        $this->assertEquals('test_string', self::$instance->getReference());
    }}
