<?php
/**
 * CallTranscriptionTrackEnumTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CallTranscriptionTrackEnum;

use PHPUnit\Framework\TestCase;

/**
 * CallTranscriptionTrackEnumTest Class Doc Comment
 *
 * @description Which &#x60;track&#x60; this transcription is derived from.
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CallTranscriptionTrackEnumTest extends TestCase
{

    /**
     * Test "CallTranscriptionTrackEnum"
     */
    public function testCallTranscriptionTrackEnum()
    {
        $this->assertSame(
            ['inbound', 'outbound'],
            array_column(CallTranscriptionTrackEnum::cases(), 'value')
        );
    }
}
