<?php
/**
 * CardWidthEnumTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CardWidthEnum;

use PHPUnit\Framework\TestCase;

/**
 * CardWidthEnumTest Class Doc Comment
 *
 * @description CardWidthEnum
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CardWidthEnumTest extends TestCase
{

    /**
     * Test "CardWidthEnum"
     */
    public function testCardWidthEnum()
    {
        $this->assertSame(
            ['SMALL', 'MEDIUM'],
            array_column(CardWidthEnum::cases(), 'value')
        );
    }
}
