<?php
/**
 * ConferenceCompletedCallbackTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\ConferenceCompletedCallback;

use PHPUnit\Framework\TestCase;

/**
 * ConferenceCompletedCallbackTest Class Doc Comment
 *
 * @description The Conference Completed event is fired when the last member leaves the conference. The response to this event may not contain BXML.
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConferenceCompletedCallbackTest extends TestCase
{
    private static ConferenceCompletedCallback $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new ConferenceCompletedCallback([
            'event_type' => 'test_string',
            'event_time' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'conference_id' => 'test_string',
            'name' => 'test_string',
            'tag' => 'test_string'
        ]);
    }

    /**
     * Test "ConferenceCompletedCallback"
     */
    public function testConferenceCompletedCallback()
    {
        $this->assertInstanceOf(ConferenceCompletedCallback::class, self::$instance);
    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {
        $this->assertIsString(self::$instance->getEventType());
        $this->assertEquals('test_string', self::$instance->getEventType());
    }

    /**
     * Test attribute "event_time"
     */
    public function testPropertyEventTime()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getEventTime());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getEventTime());
    }

    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
        $this->assertIsString(self::$instance->getConferenceId());
        $this->assertEquals('test_string', self::$instance->getConferenceId());
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->assertIsString(self::$instance->getName());
        $this->assertEquals('test_string', self::$instance->getName());
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
        $this->assertIsString(self::$instance->getTag());
        $this->assertEquals('test_string', self::$instance->getTag());
    }}
