<?php
/**
 * ConferenceMemberTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\ConferenceMember;

use PHPUnit\Framework\TestCase;

/**
 * ConferenceMemberTest Class Doc Comment
 *
 * @description ConferenceMember
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConferenceMemberTest extends TestCase
{
    private static ConferenceMember $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new ConferenceMember([
            'call_id' => 'test_string',
            'conference_id' => 'test_string',
            'member_url' => 'test_string',
            'mute' => true,
            'hold' => true,
            'call_ids_to_coach' => ['test_string']
        ]);
    }

    /**
     * Test "ConferenceMember"
     */
    public function testConferenceMember()
    {
        $this->assertInstanceOf(ConferenceMember::class, self::$instance);
    }

    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->assertIsString(self::$instance->getCallId());
        $this->assertEquals('test_string', self::$instance->getCallId());
    }

    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
        $this->assertIsString(self::$instance->getConferenceId());
        $this->assertEquals('test_string', self::$instance->getConferenceId());
    }

    /**
     * Test attribute "member_url"
     */
    public function testPropertyMemberUrl()
    {
        $this->assertIsString(self::$instance->getMemberUrl());
        $this->assertEquals('test_string', self::$instance->getMemberUrl());
    }

    /**
     * Test attribute "mute"
     */
    public function testPropertyMute()
    {
        $this->assertIsBool(self::$instance->getMute());
        $this->assertTrue(self::$instance->getMute());
    }

    /**
     * Test attribute "hold"
     */
    public function testPropertyHold()
    {
        $this->assertIsBool(self::$instance->getHold());
        $this->assertTrue(self::$instance->getHold());
    }

    /**
     * Test attribute "call_ids_to_coach"
     */
    public function testPropertyCallIdsToCoach()
    {
        $this->assertIsArray(self::$instance->getCallIdsToCoach());
        $this->assertEquals(['test_string'], self::$instance->getCallIdsToCoach());
    }}
