<?php
/**
 * ConferenceRecordingAvailableCallbackTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\ConferenceRecordingAvailableCallback;
use Bandwidth\Model\FileFormatEnum;

use PHPUnit\Framework\TestCase;

/**
 * ConferenceRecordingAvailableCallbackTest Class Doc Comment
 *
 * @description The Conference Recording Available event is sent after a conference recording has been processed. It indicates that the recording is available for download.
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConferenceRecordingAvailableCallbackTest extends TestCase
{
    private static ConferenceRecordingAvailableCallback $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new ConferenceRecordingAvailableCallback([
            'event_type' => 'test_string',
            'event_time' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'conference_id' => 'test_string',
            'name' => 'test_string',
            'account_id' => 'test_string',
            'recording_id' => 'test_string',
            'channels' => 1,
            'start_time' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'end_time' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'duration' => 'test_string',
            'file_format' => FileFormatEnum::MP3,
            'media_url' => 'test_string',
            'tag' => 'test_string',
            'status' => 'test_string'
        ]);
    }

    /**
     * Test "ConferenceRecordingAvailableCallback"
     */
    public function testConferenceRecordingAvailableCallback()
    {
        $this->assertInstanceOf(ConferenceRecordingAvailableCallback::class, self::$instance);
    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {
        $this->assertIsString(self::$instance->getEventType());
        $this->assertEquals('test_string', self::$instance->getEventType());
    }

    /**
     * Test attribute "event_time"
     */
    public function testPropertyEventTime()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getEventTime());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getEventTime());
    }

    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
        $this->assertIsString(self::$instance->getConferenceId());
        $this->assertEquals('test_string', self::$instance->getConferenceId());
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->assertIsString(self::$instance->getName());
        $this->assertEquals('test_string', self::$instance->getName());
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        $this->assertIsString(self::$instance->getAccountId());
        $this->assertEquals('test_string', self::$instance->getAccountId());
    }

    /**
     * Test attribute "recording_id"
     */
    public function testPropertyRecordingId()
    {
        $this->assertIsString(self::$instance->getRecordingId());
        $this->assertEquals('test_string', self::$instance->getRecordingId());
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
        $this->assertIsInt(self::$instance->getChannels());
        $this->assertEquals(1, self::$instance->getChannels());
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getStartTime());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getStartTime());
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getEndTime());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getEndTime());
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
        $this->assertIsString(self::$instance->getDuration());
        $this->assertEquals('test_string', self::$instance->getDuration());
    }

    /**
     * Test attribute "file_format"
     */
    public function testPropertyFileFormat()
    {
        $this->assertInstanceOf(FileFormatEnum::class, self::$instance->getFileFormat());
        $this->assertSame(FileFormatEnum::MP3, self::$instance->getFileFormat());
    }

    /**
     * Test attribute "media_url"
     */
    public function testPropertyMediaUrl()
    {
        $this->assertIsString(self::$instance->getMediaUrl());
        $this->assertEquals('test_string', self::$instance->getMediaUrl());
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
        $this->assertIsString(self::$instance->getTag());
        $this->assertEquals('test_string', self::$instance->getTag());
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertIsString(self::$instance->getStatus());
        $this->assertEquals('test_string', self::$instance->getStatus());
    }}
