<?php
/**
 * CreateSyncLookupResponseTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CreateSyncLookupResponse;
use Bandwidth\Model\CreateSyncLookupResponseData;
use Bandwidth\Model\LinkSchema;
use Bandwidth\Model\LookupErrorSchema;

use PHPUnit\Framework\TestCase;

/**
 * CreateSyncLookupResponseTest Class Doc Comment
 *
 * @description CreateSyncLookupResponse
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateSyncLookupResponseTest extends TestCase
{
    private static CreateSyncLookupResponse $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new CreateSyncLookupResponse([
            'links' => [new LinkSchema([])],
            'data' => new CreateSyncLookupResponseData([]),
            'errors' => [new LookupErrorSchema([])]
        ]);
    }

    /**
     * Test "CreateSyncLookupResponse"
     */
    public function testCreateSyncLookupResponse()
    {
        $this->assertInstanceOf(CreateSyncLookupResponse::class, self::$instance);
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
        $this->assertIsArray(self::$instance->getLinks());
        $this->assertInstanceOf(LinkSchema::class, self::$instance->getLinks()[0]);
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        $this->assertInstanceOf(CreateSyncLookupResponseData::class, self::$instance->getData());
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
        $this->assertIsArray(self::$instance->getErrors());
        $this->assertInstanceOf(LookupErrorSchema::class, self::$instance->getErrors()[0]);
    }}
