<?php
/**
 * CreateEndpointRequestBaseTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CreateEndpointRequestBase;
use Bandwidth\Model\EndpointDirectionEnum;
use Bandwidth\Model\EndpointTypeEnum;

use PHPUnit\Framework\TestCase;

/**
 * CreateEndpointRequestBaseTest Class Doc Comment
 *
 * @description CreateEndpointRequestBase
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateEndpointRequestBaseTest extends TestCase
{
    private static CreateEndpointRequestBase $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new CreateEndpointRequestBase([
            'type' => EndpointTypeEnum::WEBRTC,
            'direction' => EndpointDirectionEnum::INBOUND,
            'event_callback_url' => 'test_string',
            'event_fallback_url' => 'test_string',
            'tag' => 'test_string'
        ]);
    }

    /**
     * Test "CreateEndpointRequestBase"
     */
    public function testCreateEndpointRequestBase()
    {
        $this->assertInstanceOf(CreateEndpointRequestBase::class, self::$instance);
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertInstanceOf(EndpointTypeEnum::class, self::$instance->getType());
        $this->assertSame(EndpointTypeEnum::WEBRTC, self::$instance->getType());
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
        $this->assertInstanceOf(EndpointDirectionEnum::class, self::$instance->getDirection());
        $this->assertSame(EndpointDirectionEnum::INBOUND, self::$instance->getDirection());
    }

    /**
     * Test attribute "event_callback_url"
     */
    public function testPropertyEventCallbackUrl()
    {
        $this->assertIsString(self::$instance->getEventCallbackUrl());
        $this->assertEquals('test_string', self::$instance->getEventCallbackUrl());
    }

    /**
     * Test attribute "event_fallback_url"
     */
    public function testPropertyEventFallbackUrl()
    {
        $this->assertIsString(self::$instance->getEventFallbackUrl());
        $this->assertEquals('test_string', self::$instance->getEventFallbackUrl());
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
        $this->assertIsString(self::$instance->getTag());
        $this->assertEquals('test_string', self::$instance->getTag());
    }}
