<?php
/**
 * CreateAsyncBulkLookupResponseDataTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CreateAsyncBulkLookupResponseData;
use Bandwidth\Model\InProgressLookupStatusEnum;

use PHPUnit\Framework\TestCase;

/**
 * CreateAsyncBulkLookupResponseDataTest Class Doc Comment
 *
 * @description The phone number lookup response data
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateAsyncBulkLookupResponseDataTest extends TestCase
{
    private static CreateAsyncBulkLookupResponseData $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new CreateAsyncBulkLookupResponseData([
            'request_id' => 'test_string',
            'status' => InProgressLookupStatusEnum::IN_PROGRESS
        ]);
    }

    /**
     * Test "CreateAsyncBulkLookupResponseData"
     */
    public function testCreateAsyncBulkLookupResponseData()
    {
        $this->assertInstanceOf(CreateAsyncBulkLookupResponseData::class, self::$instance);
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
        $this->assertIsString(self::$instance->getRequestId());
        $this->assertEquals('test_string', self::$instance->getRequestId());
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertInstanceOf(InProgressLookupStatusEnum::class, self::$instance->getStatus());
        $this->assertSame(InProgressLookupStatusEnum::IN_PROGRESS, self::$instance->getStatus());
    }}
