<?php
/**
 * DeviceTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\Device;
use Bandwidth\Model\DeviceStatusEnum;

use PHPUnit\Framework\TestCase;

/**
 * DeviceTest Class Doc Comment
 *
 * @description Device
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeviceTest extends TestCase
{
    private static Device $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new Device([
            'device_id' => 'test_string',
            'device_name' => 'test_string',
            'status' => DeviceStatusEnum::CONNECTED,
            'creation_timestamp' => new \DateTime('2024-01-01T00:00:00+00:00')
        ]);
    }

    /**
     * Test "Device"
     */
    public function testDevice()
    {
        $this->assertInstanceOf(Device::class, self::$instance);
    }

    /**
     * Test attribute "device_id"
     */
    public function testPropertyDeviceId()
    {
        $this->assertIsString(self::$instance->getDeviceId());
        $this->assertEquals('test_string', self::$instance->getDeviceId());
    }

    /**
     * Test attribute "device_name"
     */
    public function testPropertyDeviceName()
    {
        $this->assertIsString(self::$instance->getDeviceName());
        $this->assertEquals('test_string', self::$instance->getDeviceName());
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertInstanceOf(DeviceStatusEnum::class, self::$instance->getStatus());
        $this->assertSame(DeviceStatusEnum::CONNECTED, self::$instance->getStatus());
    }

    /**
     * Test attribute "creation_timestamp"
     */
    public function testPropertyCreationTimestamp()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getCreationTimestamp());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getCreationTimestamp());
    }}
