<?php
/**
 * EndpointsTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\EndpointStatusEnum;
use Bandwidth\Model\EndpointTypeEnum;
use Bandwidth\Model\Endpoints;

use PHPUnit\Framework\TestCase;

/**
 * EndpointsTest Class Doc Comment
 *
 * @description Endpoints
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EndpointsTest extends TestCase
{
    private static Endpoints $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new Endpoints([
            'endpoint_id' => 'test_string',
            'type' => EndpointTypeEnum::WEBRTC,
            'status' => EndpointStatusEnum::CONNECTED,
            'creation_timestamp' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'expiration_timestamp' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'tag' => 'test_string'
        ]);
    }

    /**
     * Test "Endpoints"
     */
    public function testEndpoints()
    {
        $this->assertInstanceOf(Endpoints::class, self::$instance);
    }

    /**
     * Test attribute "endpoint_id"
     */
    public function testPropertyEndpointId()
    {
        $this->assertIsString(self::$instance->getEndpointId());
        $this->assertEquals('test_string', self::$instance->getEndpointId());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertInstanceOf(EndpointTypeEnum::class, self::$instance->getType());
        $this->assertSame(EndpointTypeEnum::WEBRTC, self::$instance->getType());
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertInstanceOf(EndpointStatusEnum::class, self::$instance->getStatus());
        $this->assertSame(EndpointStatusEnum::CONNECTED, self::$instance->getStatus());
    }

    /**
     * Test attribute "creation_timestamp"
     */
    public function testPropertyCreationTimestamp()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getCreationTimestamp());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getCreationTimestamp());
    }

    /**
     * Test attribute "expiration_timestamp"
     */
    public function testPropertyExpirationTimestamp()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getExpirationTimestamp());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getExpirationTimestamp());
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
        $this->assertIsString(self::$instance->getTag());
        $this->assertEquals('test_string', self::$instance->getTag());
    }}
