<?php
/**
 * LatestMessageDeliveryStatusEnumTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\LatestMessageDeliveryStatusEnum;

use PHPUnit\Framework\TestCase;

/**
 * LatestMessageDeliveryStatusEnumTest Class Doc Comment
 *
 * @description [DNI-Only](#section/DNI-Only). The current delivery status of the phone number. - ACTIVE: A message was successfully sent to the number (delivery code 0). - DEACTIVATED: A message was not delivered to a number (delivery code 720) - UNKNOWN: Bandwidth cannot find an delivery status entry for the number. - NOT_ENABLED: The phone number is not enabled for messaging, so there is no delivery status information.
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LatestMessageDeliveryStatusEnumTest extends TestCase
{

    /**
     * Test "LatestMessageDeliveryStatusEnum"
     */
    public function testLatestMessageDeliveryStatusEnum()
    {
        $this->assertSame(
            ['ACTIVE', 'DEACTIVATED', 'UNKNOWN', 'NOT_ENABLED'],
            array_column(LatestMessageDeliveryStatusEnum::cases(), 'value')
        );
    }
}
