<?php
/**
 * LinksObjectTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\LinksObject;

use PHPUnit\Framework\TestCase;

/**
 * LinksObjectTest Class Doc Comment
 *
 * @description LinksObject
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LinksObjectTest extends TestCase
{
    private static LinksObject $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new LinksObject([
            'first' => 'test_string',
            'next' => 'test_string',
            'previous' => 'test_string',
            'last' => 'test_string'
        ]);
    }

    /**
     * Test "LinksObject"
     */
    public function testLinksObject()
    {
        $this->assertInstanceOf(LinksObject::class, self::$instance);
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
        $this->assertIsString(self::$instance->getFirst());
        $this->assertEquals('test_string', self::$instance->getFirst());
    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {
        $this->assertIsString(self::$instance->getNext());
        $this->assertEquals('test_string', self::$instance->getNext());
    }

    /**
     * Test attribute "previous"
     */
    public function testPropertyPrevious()
    {
        $this->assertIsString(self::$instance->getPrevious());
        $this->assertEquals('test_string', self::$instance->getPrevious());
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
        $this->assertIsString(self::$instance->getLast());
        $this->assertEquals('test_string', self::$instance->getLast());
    }}
