<?php
/**
 * LookupErrorSchemaTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\LookupErrorSchema;
use Bandwidth\Model\LookupErrorSchemaMeta;

use PHPUnit\Framework\TestCase;

/**
 * LookupErrorSchemaTest Class Doc Comment
 *
 * @description LookupErrorSchema
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LookupErrorSchemaTest extends TestCase
{
    private static LookupErrorSchema $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new LookupErrorSchema([
            'code' => 'test_string',
            'description' => 'test_string',
            'type' => 'test_string',
            'meta' => new LookupErrorSchemaMeta([])
        ]);
    }

    /**
     * Test "LookupErrorSchema"
     */
    public function testLookupErrorSchema()
    {
        $this->assertInstanceOf(LookupErrorSchema::class, self::$instance);
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        $this->assertIsString(self::$instance->getCode());
        $this->assertEquals('test_string', self::$instance->getCode());
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        $this->assertIsString(self::$instance->getDescription());
        $this->assertEquals('test_string', self::$instance->getDescription());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertIsString(self::$instance->getType());
        $this->assertEquals('test_string', self::$instance->getType());
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
        $this->assertInstanceOf(LookupErrorSchemaMeta::class, self::$instance->getMeta());
    }}
