<?php
/**
 * LookupResultTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\DeactivationEventEnum;
use Bandwidth\Model\LatestMessageDeliveryStatusEnum;
use Bandwidth\Model\LineTypeEnum;
use Bandwidth\Model\LookupResult;

use PHPUnit\Framework\TestCase;

/**
 * LookupResultTest Class Doc Comment
 *
 * @description Carrier information results for the specified telephone number.
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LookupResultTest extends TestCase
{
    private static LookupResult $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new LookupResult([
            'phone_number' => 'test_string',
            'line_type' => LineTypeEnum::FIXED,
            'messaging_provider' => 'test_string',
            'voice_provider' => 'test_string',
            'country_code_a3' => 'test_string',
            'deactivation_reporter' => 'test_string',
            'deactivation_date' => 'test_string',
            'deactivation_event' => DeactivationEventEnum::DEACTIVATED,
            'latest_message_delivery_status' => LatestMessageDeliveryStatusEnum::ACTIVE,
            'initial_message_delivery_status_date' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'latest_message_delivery_status_date' => new \DateTime('2024-01-01T00:00:00+00:00'),
            'rcs_enabled' => true
        ]);
    }

    /**
     * Test "LookupResult"
     */
    public function testLookupResult()
    {
        $this->assertInstanceOf(LookupResult::class, self::$instance);
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
        $this->assertIsString(self::$instance->getPhoneNumber());
        $this->assertEquals('test_string', self::$instance->getPhoneNumber());
    }

    /**
     * Test attribute "line_type"
     */
    public function testPropertyLineType()
    {
        $this->assertInstanceOf(LineTypeEnum::class, self::$instance->getLineType());
        $this->assertSame(LineTypeEnum::FIXED, self::$instance->getLineType());
    }

    /**
     * Test attribute "messaging_provider"
     */
    public function testPropertyMessagingProvider()
    {
        $this->assertIsString(self::$instance->getMessagingProvider());
        $this->assertEquals('test_string', self::$instance->getMessagingProvider());
    }

    /**
     * Test attribute "voice_provider"
     */
    public function testPropertyVoiceProvider()
    {
        $this->assertIsString(self::$instance->getVoiceProvider());
        $this->assertEquals('test_string', self::$instance->getVoiceProvider());
    }

    /**
     * Test attribute "country_code_a3"
     */
    public function testPropertyCountryCodeA3()
    {
        $this->assertIsString(self::$instance->getCountryCodeA3());
        $this->assertEquals('test_string', self::$instance->getCountryCodeA3());
    }

    /**
     * Test attribute "deactivation_reporter"
     */
    public function testPropertyDeactivationReporter()
    {
        $this->assertIsString(self::$instance->getDeactivationReporter());
        $this->assertEquals('test_string', self::$instance->getDeactivationReporter());
    }

    /**
     * Test attribute "deactivation_date"
     */
    public function testPropertyDeactivationDate()
    {
        $this->assertIsString(self::$instance->getDeactivationDate());
        $this->assertEquals('test_string', self::$instance->getDeactivationDate());
    }

    /**
     * Test attribute "deactivation_event"
     */
    public function testPropertyDeactivationEvent()
    {
        $this->assertInstanceOf(DeactivationEventEnum::class, self::$instance->getDeactivationEvent());
        $this->assertSame(DeactivationEventEnum::DEACTIVATED, self::$instance->getDeactivationEvent());
    }

    /**
     * Test attribute "latest_message_delivery_status"
     */
    public function testPropertyLatestMessageDeliveryStatus()
    {
        $this->assertInstanceOf(LatestMessageDeliveryStatusEnum::class, self::$instance->getLatestMessageDeliveryStatus());
        $this->assertSame(LatestMessageDeliveryStatusEnum::ACTIVE, self::$instance->getLatestMessageDeliveryStatus());
    }

    /**
     * Test attribute "initial_message_delivery_status_date"
     */
    public function testPropertyInitialMessageDeliveryStatusDate()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getInitialMessageDeliveryStatusDate());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getInitialMessageDeliveryStatusDate());
    }

    /**
     * Test attribute "latest_message_delivery_status_date"
     */
    public function testPropertyLatestMessageDeliveryStatusDate()
    {
        $this->assertInstanceOf(\DateTime::class, self::$instance->getLatestMessageDeliveryStatusDate());
        $this->assertEquals(new \DateTime('2024-01-01T00:00:00+00:00'), self::$instance->getLatestMessageDeliveryStatusDate());
    }

    /**
     * Test attribute "rcs_enabled"
     */
    public function testPropertyRcsEnabled()
    {
        $this->assertIsBool(self::$instance->getRcsEnabled());
        $this->assertTrue(self::$instance->getRcsEnabled());
    }}
