<?php
/**
 * MachineDetectionResultTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\MachineDetectionResult;

use PHPUnit\Framework\TestCase;

/**
 * MachineDetectionResultTest Class Doc Comment
 *
 * @description (optional) if machine detection was requested in sync mode, the result will be specified here. Possible values are the same as the async counterpart: Machine Detection Complete
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MachineDetectionResultTest extends TestCase
{
    private static MachineDetectionResult $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new MachineDetectionResult([
            'value' => 'test_string',
            'duration' => 'test_string'
        ]);
    }

    /**
     * Test "MachineDetectionResult"
     */
    public function testMachineDetectionResult()
    {
        $this->assertInstanceOf(MachineDetectionResult::class, self::$instance);
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        $this->assertIsString(self::$instance->getValue());
        $this->assertEquals('test_string', self::$instance->getValue());
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
        $this->assertIsString(self::$instance->getDuration());
        $this->assertEquals('test_string', self::$instance->getDuration());
    }}
