<?php
/**
 * MachineDetectionConfigurationTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CallbackMethodEnum;
use Bandwidth\Model\MachineDetectionConfiguration;
use Bandwidth\Model\MachineDetectionModeEnum;

use PHPUnit\Framework\TestCase;

/**
 * MachineDetectionConfigurationTest Class Doc Comment
 *
 * @description The machine detection request used to perform &lt;a href&#x3D;&#39;/docs/voice/guides/machineDetection&#39;&gt;machine detection&lt;/a&gt; on the call. Currently, there is an issue where decimal values are not getting processed correctly. Please use whole number values. We are working to resolve this issue. Please contact Bandwidth Support if you need more information.
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MachineDetectionConfigurationTest extends TestCase
{
    private static MachineDetectionConfiguration $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new MachineDetectionConfiguration([
            'mode' => MachineDetectionModeEnum::SYNC,
            'detection_timeout' => 1.5,
            'silence_timeout' => 1.5,
            'speech_threshold' => 1.5,
            'speech_end_threshold' => 1.5,
            'machine_speech_end_threshold' => 1.5,
            'delay_result' => true,
            'callback_url' => 'test_string',
            'callback_method' => CallbackMethodEnum::GET,
            'username' => 'test_string',
            'password' => 'test_string',
            'fallback_url' => 'test_string',
            'fallback_method' => CallbackMethodEnum::GET,
            'fallback_username' => 'test_string',
            'fallback_password' => 'test_string'
        ]);
    }

    /**
     * Test "MachineDetectionConfiguration"
     */
    public function testMachineDetectionConfiguration()
    {
        $this->assertInstanceOf(MachineDetectionConfiguration::class, self::$instance);
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
        $this->assertInstanceOf(MachineDetectionModeEnum::class, self::$instance->getMode());
        $this->assertSame(MachineDetectionModeEnum::SYNC, self::$instance->getMode());
    }

    /**
     * Test attribute "detection_timeout"
     */
    public function testPropertyDetectionTimeout()
    {
        $this->assertIsFloat(self::$instance->getDetectionTimeout());
        $this->assertEquals(1.5, self::$instance->getDetectionTimeout());
    }

    /**
     * Test attribute "silence_timeout"
     */
    public function testPropertySilenceTimeout()
    {
        $this->assertIsFloat(self::$instance->getSilenceTimeout());
        $this->assertEquals(1.5, self::$instance->getSilenceTimeout());
    }

    /**
     * Test attribute "speech_threshold"
     */
    public function testPropertySpeechThreshold()
    {
        $this->assertIsFloat(self::$instance->getSpeechThreshold());
        $this->assertEquals(1.5, self::$instance->getSpeechThreshold());
    }

    /**
     * Test attribute "speech_end_threshold"
     */
    public function testPropertySpeechEndThreshold()
    {
        $this->assertIsFloat(self::$instance->getSpeechEndThreshold());
        $this->assertEquals(1.5, self::$instance->getSpeechEndThreshold());
    }

    /**
     * Test attribute "machine_speech_end_threshold"
     */
    public function testPropertyMachineSpeechEndThreshold()
    {
        $this->assertIsFloat(self::$instance->getMachineSpeechEndThreshold());
        $this->assertEquals(1.5, self::$instance->getMachineSpeechEndThreshold());
    }

    /**
     * Test attribute "delay_result"
     */
    public function testPropertyDelayResult()
    {
        $this->assertIsBool(self::$instance->getDelayResult());
        $this->assertTrue(self::$instance->getDelayResult());
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
        $this->assertIsString(self::$instance->getCallbackUrl());
        $this->assertEquals('test_string', self::$instance->getCallbackUrl());
    }

    /**
     * Test attribute "callback_method"
     */
    public function testPropertyCallbackMethod()
    {
        $this->assertInstanceOf(CallbackMethodEnum::class, self::$instance->getCallbackMethod());
        $this->assertSame(CallbackMethodEnum::GET, self::$instance->getCallbackMethod());
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
        $this->assertIsString(self::$instance->getUsername());
        $this->assertEquals('test_string', self::$instance->getUsername());
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        $this->assertIsString(self::$instance->getPassword());
        $this->assertEquals('test_string', self::$instance->getPassword());
    }

    /**
     * Test attribute "fallback_url"
     */
    public function testPropertyFallbackUrl()
    {
        $this->assertIsString(self::$instance->getFallbackUrl());
        $this->assertEquals('test_string', self::$instance->getFallbackUrl());
    }

    /**
     * Test attribute "fallback_method"
     */
    public function testPropertyFallbackMethod()
    {
        $this->assertInstanceOf(CallbackMethodEnum::class, self::$instance->getFallbackMethod());
        $this->assertSame(CallbackMethodEnum::GET, self::$instance->getFallbackMethod());
    }

    /**
     * Test attribute "fallback_username"
     */
    public function testPropertyFallbackUsername()
    {
        $this->assertIsString(self::$instance->getFallbackUsername());
        $this->assertEquals('test_string', self::$instance->getFallbackUsername());
    }

    /**
     * Test attribute "fallback_password"
     */
    public function testPropertyFallbackPassword()
    {
        $this->assertIsString(self::$instance->getFallbackPassword());
        $this->assertEquals('test_string', self::$instance->getFallbackPassword());
    }}
