<?php
/**
 * MessagesListTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\ListMessageItem;
use Bandwidth\Model\MessagesList;
use Bandwidth\Model\PageInfo;

use PHPUnit\Framework\TestCase;

/**
 * MessagesListTest Class Doc Comment
 *
 * @description MessagesList
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MessagesListTest extends TestCase
{
    private static MessagesList $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new MessagesList([
            'total_count' => 1,
            'page_info' => new PageInfo([]),
            'messages' => [new ListMessageItem([])]
        ]);
    }

    /**
     * Test "MessagesList"
     */
    public function testMessagesList()
    {
        $this->assertInstanceOf(MessagesList::class, self::$instance);
    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {
        $this->assertIsInt(self::$instance->getTotalCount());
        $this->assertEquals(1, self::$instance->getTotalCount());
    }

    /**
     * Test attribute "page_info"
     */
    public function testPropertyPageInfo()
    {
        $this->assertInstanceOf(PageInfo::class, self::$instance->getPageInfo());
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
        $this->assertIsArray(self::$instance->getMessages());
        $this->assertInstanceOf(ListMessageItem::class, self::$instance->getMessages()[0]);
    }}
