<?php
/**
 * MultiChannelActionTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\MultiChannelAction;
use Bandwidth\Model\MultiChannelActionCalendarEvent;
use Bandwidth\Model\RbmActionBase;
use Bandwidth\Model\RbmActionDial;
use Bandwidth\Model\RbmActionOpenUrl;
use Bandwidth\Model\RbmActionViewLocation;
use Bandwidth\ObjectSerializer;

use PHPUnit\Framework\TestCase;

/**
 * MultiChannelActionTest Class Doc Comment
 *
 * @description MultiChannelAction
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MultiChannelActionTest extends TestCase
{
    /**
     * Test "MultiChannelAction"
     */
    public function testMultiChannelAction()
    {
        $this->assertSame(
            [
                RbmActionBase::class,
                RbmActionDial::class,
                RbmActionViewLocation::class,
                MultiChannelActionCalendarEvent::class,
                RbmActionOpenUrl::class
            ],
            array_map(fn($type) => ltrim($type, '\\'), MultiChannelAction::getAnyOfTypes())
        );
        $this->assertSame('type', MultiChannelAction::getAnyOfDiscriminator());
        $this->assertSame(
            [
                'CREATE_CALENDAR_EVENT' => MultiChannelActionCalendarEvent::class,
                'DIAL_PHONE' => RbmActionDial::class,
                'OPEN_URL' => RbmActionOpenUrl::class,
                'REPLY' => RbmActionBase::class,
                'REQUEST_LOCATION' => RbmActionBase::class,
                'SHOW_LOCATION' => RbmActionViewLocation::class
            ],
            array_map(fn($type) => ltrim($type, '\\'), MultiChannelAction::getAnyOfDiscriminatorMappings())
        );
    }

    /**
     * Test that each discriminator value deserializes to its mapped type
     *
     * @dataProvider discriminatorProvider
     */
    public function testDeserializeResolvesDiscriminator(string $type, string $expected)
    {
        $result = ObjectSerializer::deserialize((object) ['type' => $type], MultiChannelAction::class);

        $this->assertInstanceOf($expected, $result);
        $this->assertSame($type, $result->getType()->value);
    }

    /**
     * Test that an unmapped discriminator value is rejected
     */
    public function testDeserializeRejectsUnknownDiscriminator()
    {
        $this->expectException(\InvalidArgumentException::class);

        ObjectSerializer::deserialize((object) ['type' => 'NOT_AN_ACTION'], MultiChannelAction::class);
    }

    /**
     * @return array<string, array{0: string, 1: class-string}>
     */
    public static function discriminatorProvider(): array
    {
        return [
            'CREATE_CALENDAR_EVENT' => ['CREATE_CALENDAR_EVENT', MultiChannelActionCalendarEvent::class],
            'DIAL_PHONE' => ['DIAL_PHONE', RbmActionDial::class],
            'OPEN_URL' => ['OPEN_URL', RbmActionOpenUrl::class],
            'REPLY' => ['REPLY', RbmActionBase::class],
            'REQUEST_LOCATION' => ['REQUEST_LOCATION', RbmActionBase::class],
            'SHOW_LOCATION' => ['SHOW_LOCATION', RbmActionViewLocation::class]
        ];
    }
}
