<?php
/**
 * MultiChannelChannelListSMSObjectTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\MultiChannelChannelListSMSObject;
use Bandwidth\Model\MultiChannelMessageChannelEnum;
use Bandwidth\Model\SmsMessageContent;

use PHPUnit\Framework\TestCase;

/**
 * MultiChannelChannelListSMSObjectTest Class Doc Comment
 *
 * @description MultiChannelChannelListSMSObject
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MultiChannelChannelListSMSObjectTest extends TestCase
{
    private static MultiChannelChannelListSMSObject $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new MultiChannelChannelListSMSObject([
            'from' => 'test_string',
            'application_id' => 'test_string',
            'channel' => MultiChannelMessageChannelEnum::RBM,
            'content' => new SmsMessageContent([])
        ]);
    }

    /**
     * Test "MultiChannelChannelListSMSObject"
     */
    public function testMultiChannelChannelListSMSObject()
    {
        $this->assertInstanceOf(MultiChannelChannelListSMSObject::class, self::$instance);
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
        $this->assertIsString(self::$instance->getFrom());
        $this->assertEquals('test_string', self::$instance->getFrom());
    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {
        $this->assertIsString(self::$instance->getApplicationId());
        $this->assertEquals('test_string', self::$instance->getApplicationId());
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
        $this->assertInstanceOf(MultiChannelMessageChannelEnum::class, self::$instance->getChannel());
        $this->assertSame(MultiChannelMessageChannelEnum::RBM, self::$instance->getChannel());
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
        $this->assertInstanceOf(SmsMessageContent::class, self::$instance->getContent());
    }}
