<?php
/**
 * SipConnectionMetadataTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\SipConnectionMetadata;
use Bandwidth\Model\SipCredentials;

use PHPUnit\Framework\TestCase;

/**
 * SipConnectionMetadataTest Class Doc Comment
 *
 * @description SipConnectionMetadata
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SipConnectionMetadataTest extends TestCase
{
    private static SipConnectionMetadata $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new SipConnectionMetadata([
            'ip_address' => 'test_string',
            'port' => 1,
            'credentials' => new SipCredentials([]),
            'uui_header' => 'test_string'
        ]);
    }

    /**
     * Test "SipConnectionMetadata"
     */
    public function testSipConnectionMetadata()
    {
        $this->assertInstanceOf(SipConnectionMetadata::class, self::$instance);
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
        $this->assertIsString(self::$instance->getIpAddress());
        $this->assertEquals('test_string', self::$instance->getIpAddress());
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
        $this->assertIsInt(self::$instance->getPort());
        $this->assertEquals(1, self::$instance->getPort());
    }

    /**
     * Test attribute "credentials"
     */
    public function testPropertyCredentials()
    {
        $this->assertInstanceOf(SipCredentials::class, self::$instance->getCredentials());
    }

    /**
     * Test attribute "uui_header"
     */
    public function testPropertyUuiHeader()
    {
        $this->assertIsString(self::$instance->getUuiHeader());
        $this->assertEquals('test_string', self::$instance->getUuiHeader());
    }}
