<?php
/**
 * TfvBasicAuthenticationTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\TfvBasicAuthentication;

use PHPUnit\Framework\TestCase;

/**
 * TfvBasicAuthenticationTest Class Doc Comment
 *
 * @description TfvBasicAuthentication
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TfvBasicAuthenticationTest extends TestCase
{
    private static TfvBasicAuthentication $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new TfvBasicAuthentication([
            'username' => 'test_string',
            'password' => 'test_string'
        ]);
    }

    /**
     * Test "TfvBasicAuthentication"
     */
    public function testTfvBasicAuthentication()
    {
        $this->assertInstanceOf(TfvBasicAuthentication::class, self::$instance);
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
        $this->assertIsString(self::$instance->getUsername());
        $this->assertEquals('test_string', self::$instance->getUsername());
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        $this->assertIsString(self::$instance->getPassword());
        $this->assertEquals('test_string', self::$instance->getPassword());
    }}
