<?php
/**
 * UpdateCallTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\CallStateEnum;
use Bandwidth\Model\RedirectMethodEnum;
use Bandwidth\Model\UpdateCall;

use PHPUnit\Framework\TestCase;

/**
 * UpdateCallTest Class Doc Comment
 *
 * @description UpdateCall
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateCallTest extends TestCase
{
    private static UpdateCall $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new UpdateCall([
            'state' => CallStateEnum::ACTIVE,
            'redirect_url' => 'test_string',
            'redirect_method' => RedirectMethodEnum::GET,
            'username' => 'test_string',
            'password' => 'test_string',
            'redirect_fallback_url' => 'test_string',
            'redirect_fallback_method' => RedirectMethodEnum::GET,
            'fallback_username' => 'test_string',
            'fallback_password' => 'test_string',
            'tag' => 'test_string'
        ]);
    }

    /**
     * Test "UpdateCall"
     */
    public function testUpdateCall()
    {
        $this->assertInstanceOf(UpdateCall::class, self::$instance);
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        $this->assertInstanceOf(CallStateEnum::class, self::$instance->getState());
        $this->assertSame(CallStateEnum::ACTIVE, self::$instance->getState());
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
        $this->assertIsString(self::$instance->getRedirectUrl());
        $this->assertEquals('test_string', self::$instance->getRedirectUrl());
    }

    /**
     * Test attribute "redirect_method"
     */
    public function testPropertyRedirectMethod()
    {
        $this->assertInstanceOf(RedirectMethodEnum::class, self::$instance->getRedirectMethod());
        $this->assertSame(RedirectMethodEnum::GET, self::$instance->getRedirectMethod());
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
        $this->assertIsString(self::$instance->getUsername());
        $this->assertEquals('test_string', self::$instance->getUsername());
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        $this->assertIsString(self::$instance->getPassword());
        $this->assertEquals('test_string', self::$instance->getPassword());
    }

    /**
     * Test attribute "redirect_fallback_url"
     */
    public function testPropertyRedirectFallbackUrl()
    {
        $this->assertIsString(self::$instance->getRedirectFallbackUrl());
        $this->assertEquals('test_string', self::$instance->getRedirectFallbackUrl());
    }

    /**
     * Test attribute "redirect_fallback_method"
     */
    public function testPropertyRedirectFallbackMethod()
    {
        $this->assertInstanceOf(RedirectMethodEnum::class, self::$instance->getRedirectFallbackMethod());
        $this->assertSame(RedirectMethodEnum::GET, self::$instance->getRedirectFallbackMethod());
    }

    /**
     * Test attribute "fallback_username"
     */
    public function testPropertyFallbackUsername()
    {
        $this->assertIsString(self::$instance->getFallbackUsername());
        $this->assertEquals('test_string', self::$instance->getFallbackUsername());
    }

    /**
     * Test attribute "fallback_password"
     */
    public function testPropertyFallbackPassword()
    {
        $this->assertIsString(self::$instance->getFallbackPassword());
        $this->assertEquals('test_string', self::$instance->getFallbackPassword());
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
        $this->assertIsString(self::$instance->getTag());
        $this->assertEquals('test_string', self::$instance->getTag());
    }}
