<?php
/**
 * UpdateConferenceMemberTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\UpdateConferenceMember;

use PHPUnit\Framework\TestCase;

/**
 * UpdateConferenceMemberTest Class Doc Comment
 *
 * @description UpdateConferenceMember
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateConferenceMemberTest extends TestCase
{
    private static UpdateConferenceMember $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new UpdateConferenceMember([
            'mute' => true,
            'hold' => true,
            'call_ids_to_coach' => ['test_string']
        ]);
    }

    /**
     * Test "UpdateConferenceMember"
     */
    public function testUpdateConferenceMember()
    {
        $this->assertInstanceOf(UpdateConferenceMember::class, self::$instance);
    }

    /**
     * Test attribute "mute"
     */
    public function testPropertyMute()
    {
        $this->assertIsBool(self::$instance->getMute());
        $this->assertTrue(self::$instance->getMute());
    }

    /**
     * Test attribute "hold"
     */
    public function testPropertyHold()
    {
        $this->assertIsBool(self::$instance->getHold());
        $this->assertTrue(self::$instance->getHold());
    }

    /**
     * Test attribute "call_ids_to_coach"
     */
    public function testPropertyCallIdsToCoach()
    {
        $this->assertIsArray(self::$instance->getCallIdsToCoach());
        $this->assertEquals(['test_string'], self::$instance->getCallIdsToCoach());
    }}
