<?php
/**
 * VoiceCodeResponseTest
 *
 * PHP version 8.1
 *
 * @package  Bandwidth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bandwidth\Test\Unit\Model;

use Bandwidth\Model\VoiceCodeResponse;

use PHPUnit\Framework\TestCase;

/**
 * VoiceCodeResponseTest Class Doc Comment
 *
 * @description VoiceCodeResponse
 * @package     Bandwidth
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VoiceCodeResponseTest extends TestCase
{
    private static VoiceCodeResponse $instance;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
        self::$instance = new VoiceCodeResponse([
            'call_id' => 'test_string'
        ]);
    }

    /**
     * Test "VoiceCodeResponse"
     */
    public function testVoiceCodeResponse()
    {
        $this->assertInstanceOf(VoiceCodeResponse::class, self::$instance);
    }

    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->assertIsString(self::$instance->getCallId());
        $this->assertEquals('test_string', self::$instance->getCallId());
    }}
