<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const DEFAULT_ = "default";

    /**
     * TODO: Write general description for this element
     */
    const MESSAGINGDEFAULT = "MessagingDefault";

    /**
     * TODO: Write general description for this element
     */
    const VOICEDEFAULT = "VoiceDefault";
}
