<?php
/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\TwoFactorAuth\Models;

/**
 * @todo Write general description for this model
 */
class TwoFactorVerifyRequestSchema implements \JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $to public property
     */
    public $to;

    /**
     * @todo Write general description for this property
     * @var string|null $from public property
     */
    public $from;

    /**
     * @todo Write general description for this property
     * @var string|null $applicationId public property
     */
    public $applicationId;

    /**
     * @todo Write general description for this property
     * @var string|null $scope public property
     */
    public $scope;

    /**
     * @todo Write general description for this property
     * @var string|null $code public property
     */
    public $code;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->to            = func_get_arg(0);
            $this->from          = func_get_arg(1);
            $this->applicationId = func_get_arg(2);
            $this->scope         = func_get_arg(3);
            $this->code          = func_get_arg(4);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['to']            = $this->to;
        $json['from']          = $this->from;
        $json['applicationId'] = $this->applicationId;
        $json['scope']         = $this->scope;
        $json['code']          = $this->code;

        return array_filter($json);
    }
}
