<?php

declare(strict_types=1);

/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthLib\TwoFactorAuth\Models;

class TwoFactorMessagingResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $messageId;

    /**
     * Returns Message Id.
     */
    public function getMessageId(): ?string
    {
        return $this->messageId;
    }

    /**
     * Sets Message Id.
     *
     * @maps messageId
     */
    public function setMessageId(?string $messageId): void
    {
        $this->messageId = $messageId;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['messageId'] = $this->messageId;

        return array_filter($json, function ($val) {
            return $val !== null;
        });
    }
}
