name: Validate SDK

on:
  pull_request:
    branches:
      - 'master'

jobs:
  deploy:
    name: Validate SDK 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate
      uses: ./.github/actions/validate
