name: Validate SDK

on:
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    name: Validate SDK 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate
      uses: ./.github/actions/validate
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        VOICE_APPLICATION_ID: ${{ secrets.VOICE_APPLICATION_ID }}
        MESSAGING_APPLICATION_ID: ${{ secrets.MESSAGING_APPLICATION_ID }}
        CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
        PHONE_NUMBER_OUTBOUND: ${{ secrets.PHONE_NUMBER_OUTBOUND }}
        PHONE_NUMBER_INBOUND: ${{ secrets.PHONE_NUMBER_INBOUND }}
        MFA_MESSAGING_APPLICATION_ID: ${{ secrets.MFA_MESSAGING_APPLICATION_ID }}
        MFA_VOICE_APPLICATION_ID: ${{ secrets.MFA_VOICE_APPLICATION_ID }}
        PHONE_NUMBER_MFA: ${{ secrets.PHONE_NUMBER_MFA }}
