name: Validate SDK

on:
  schedule:
    - cron: "0 4 * * *"
  pull_request:

jobs:
  deploy:
    name: Validate SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate
      uses: ./.github/actions/validate
      env:
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
        BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
        BW_NUMBER: ${{ secrets.BW_NUMBER }}
        USER_NUMBER: ${{ secrets.USER_NUMBER }}
        BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
    - uses: Bandwidth/build-notify-slack-action@v1.0.0
      if: failure() && !github.event.pull_request.draft
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: ${{ secrets.SLACK_CHANNEL }}
